/* tslint:disable */
/* eslint-disable */
/**
 * Rsquare Manage Server
 * Api Document
 *
 * The version of the OpenAPI document: V22.20.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BldClnBld
 */
export interface BldClnBld {
    /**
     * 
     * @type {string}
     * @memberof BldClnBld
     */
    'addr'?: string;
    /**
     * 
     * @type {string}
     * @memberof BldClnBld
     */
    'bldId'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof BldClnBld
     */
    'lwh'?: boolean;
}

