/* tslint:disable */
/* eslint-disable */
/**
 * Rsquare Manage Server
 * Api Document
 *
 * The version of the OpenAPI document: V22.20.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { GetRegnStatOut } from './get-regn-stat-out';

/**
 * 
 * @export
 * @interface GetObjStatOut
 */
export interface GetObjStatOut {
    /**
     * 
     * @type {GetRegnStatOut}
     * @memberof GetObjStatOut
     */
    'bldCount'?: GetRegnStatOut;
    /**
     * 
     * @type {GetRegnStatOut}
     * @memberof GetObjStatOut
     */
    'prdCount'?: GetRegnStatOut;
}

