/* tslint:disable */
/* eslint-disable */
/**
 * Rsquare Manage Server
 * Api Document
 *
 * The version of the OpenAPI document: V22.20.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetBldPointOut
 */
export interface GetBldPointOut {
    /**
     * 
     * @type {string}
     * @memberof GetBldPointOut
     */
    'addr': string;
    /**
     * 
     * @type {string}
     * @memberof GetBldPointOut
     */
    'bldId': string;
    /**
     * 
     * @type {string}
     * @memberof GetBldPointOut
     */
    'bldName': string;
    /**
     * 
     * @type {string}
     * @memberof GetBldPointOut
     */
    'iclTaskStatCd': string;
    /**
     * 
     * @type {number}
     * @memberof GetBldPointOut
     */
    'lat': number;
    /**
     * 
     * @type {number}
     * @memberof GetBldPointOut
     */
    'lng': number;
}

