/* tslint:disable */
/* eslint-disable */
/**
 * Rsquare Manage Server
 * Api Document
 *
 * The version of the OpenAPI document: V22.20.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetOtreqAssignOut
 */
export interface GetOtreqAssignOut {
    /**
     * 
     * @type {string}
     * @memberof GetOtreqAssignOut
     */
    'addr'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetOtreqAssignOut
     */
    'bldId'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetOtreqAssignOut
     */
    'bltypPtbName'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetOtreqAssignOut
     */
    'checkValues'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetOtreqAssignOut
     */
    'conclcPtbName'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetOtreqAssignOut
     */
    'curPtbName'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetOtreqAssignOut
     */
    'iclReqStatName'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetOtreqAssignOut
     */
    'procDy'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetOtreqAssignOut
     */
    'procStat'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetOtreqAssignOut
     */
    'ptb'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetOtreqAssignOut
     */
    'reqCtn'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetOtreqAssignOut
     */
    'reqDy'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetOtreqAssignOut
     */
    'reqUser'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetOtreqAssignOut
     */
    'reqUserId'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetOtreqAssignOut
     */
    'taskId'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetOtreqAssignOut
     */
    'workId'?: string;
}

