/* tslint:disable */
/* eslint-disable */
/**
 * Rsquare Manage Server
 * Api Document
 *
 * The version of the OpenAPI document: V22.20.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetUserDeviceIn
 */
export interface GetUserDeviceIn {
    /**
     * 
     * @type {string}
     * @memberof GetUserDeviceIn
     */
    'userId'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetUserDeviceIn
     */
    'deviceInfo'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetUserDeviceIn
     */
    'userToken'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetUserDeviceIn
     */
    'tokenCreatedDt'?: string;
}

