/* tslint:disable */
/* eslint-disable */
/**
 * Rsquare Manage Server
 * Api Document
 *
 * The version of the OpenAPI document: V22.20.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetEntfyDeptListOut
 */
export interface GetEntfyDeptListOut {
    /**
     * 
     * @type {string}
     * @memberof GetEntfyDeptListOut
     */
    'createDt'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetEntfyDeptListOut
     */
    'createUserName'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetEntfyDeptListOut
     */
    'deptId'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetEntfyDeptListOut
     */
    'deptName'?: string;
}

