/* tslint:disable */
/* eslint-disable */
/**
 * Rsquare Manage Server
 * Api Document
 *
 * The version of the OpenAPI document: V22.20.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetColdCallWorkListOut
 */
export interface GetColdCallWorkListOut {
    /**
     * 
     * @type {string}
     * @memberof GetColdCallWorkListOut
     */
    'asgmtDy'?: string;
    /**
     * 
     * @type {number}
     * @memberof GetColdCallWorkListOut
     */
    'callCnt'?: number;
    /**
     * 
     * @type {string}
     * @memberof GetColdCallWorkListOut
     */
    'callTrialDy'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetColdCallWorkListOut
     */
    'ccalId': string;
    /**
     * 
     * @type {string}
     * @memberof GetColdCallWorkListOut
     */
    'ccalTcalResCd'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetColdCallWorkListOut
     */
    'clnId'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetColdCallWorkListOut
     */
    'clnName'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetColdCallWorkListOut
     */
    'cmplYn'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetColdCallWorkListOut
     */
    'conCollectYn'?: string;
    /**
     * 
     * @type {number}
     * @memberof GetColdCallWorkListOut
     */
    'linkedSal'?: number;
    /**
     * 
     * @type {string}
     * @memberof GetColdCallWorkListOut
     */
    'mtDueDy'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetColdCallWorkListOut
     */
    'mtStat'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetColdCallWorkListOut
     */
    'ptb'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetColdCallWorkListOut
     */
    'ptbId'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetColdCallWorkListOut
     */
    'updateDy'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetColdCallWorkListOut
     */
    'workStat'?: string;
}

