/* tslint:disable */
/* eslint-disable */
/**
 * Rsquare Manage Server
 * Api Document
 *
 * The version of the OpenAPI document: V22.20.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetBatchOut
 */
export interface GetBatchOut {
    /**
     * 
     * @type {string}
     * @memberof GetBatchOut
     */
    'batchId': string;
    /**
     * 
     * @type {string}
     * @memberof GetBatchOut
     */
    'batchName': string;
    /**
     * 
     * @type {string}
     * @memberof GetBatchOut
     */
    'batchType'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetBatchOut
     */
    'batchTypeCd'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetBatchOut
     */
    'createDt': string;
    /**
     * 
     * @type {string}
     * @memberof GetBatchOut
     */
    'createUserId'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetBatchOut
     */
    'createUserName'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetBatchOut
     */
    'cronString': string;
    /**
     * 
     * @type {string}
     * @memberof GetBatchOut
     */
    'expl'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetBatchOut
     */
    'updateDt'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetBatchOut
     */
    'updateUserId'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetBatchOut
     */
    'updateUserName'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetBatchOut
     */
    'useYn'?: string;
}

