/* tslint:disable */
/* eslint-disable */
/**
 * Rsquare Manage Server
 * Api Document
 *
 * The version of the OpenAPI document: V22.20.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetAllNewLwhChkOut
 */
export interface GetAllNewLwhChkOut {
    /**
     * 
     * @type {string}
     * @memberof GetAllNewLwhChkOut
     */
    'addr'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAllNewLwhChkOut
     */
    'createUserName'?: string;
    /**
     * 
     * @type {number}
     * @memberof GetAllNewLwhChkOut
     */
    'dpstTtwn'?: number;
    /**
     * 
     * @type {string}
     * @memberof GetAllNewLwhChkOut
     */
    'flrom'?: string;
    /**
     * 
     * @type {number}
     * @memberof GetAllNewLwhChkOut
     */
    'glaPy'?: number;
    /**
     * 
     * @type {string}
     * @memberof GetAllNewLwhChkOut
     */
    'lwhId'?: string;
    /**
     * 
     * @type {number}
     * @memberof GetAllNewLwhChkOut
     */
    'mtnFeeTtwn'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetAllNewLwhChkOut
     */
    'nlaPy'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetAllNewLwhChkOut
     */
    'nlaRate'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetAllNewLwhChkOut
     */
    'rentFeeTtwn'?: number;
}

