/* tslint:disable */
/* eslint-disable */
/**
 * Rsquare Manage Server
 * Api Document
 *
 * The version of the OpenAPI document: V22.20.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetProposalPrdIn
 */
export interface GetProposalPrdIn {
    /**
     * 
     * @type {boolean}
     * @memberof GetProposalPrdIn
     */
    'lwh'?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof GetProposalPrdIn
     */
    'prdId'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof GetProposalPrdIn
     */
    'coverYn'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetProposalPrdIn
     */
    'contactYn'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetProposalPrdIn
     */
    'tipYn'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetProposalPrdIn
     */
    'fictureYn'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetProposalPrdIn
     */
    'addressYn'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetProposalPrdIn
     */
    'costOfMeterYn'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GetProposalPrdIn
     */
    'isLwh'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GetProposalPrdIn
     */
    'fireBaseToken'?: string;
}

