/* tslint:disable */
/* eslint-disable */
/**
 * Rsquare Manage Server
 * Api Document
 *
 * The version of the OpenAPI document: V22.20.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetContrRentMaintFeeOut
 */
export interface GetContrRentMaintFeeOut {
    /**
     * 
     * @type {number}
     * @memberof GetContrRentMaintFeeOut
     */
    'mtnFeeAmt'?: number;
    /**
     * 
     * @type {string}
     * @memberof GetContrRentMaintFeeOut
     */
    'prdId'?: string;
    /**
     * 
     * @type {number}
     * @memberof GetContrRentMaintFeeOut
     */
    'rentAmt'?: number;
}

