/* tslint:disable */
/* eslint-disable */
/**
 * Rsquare Manage Server
 * Api Document
 *
 * The version of the OpenAPI document: V22.20.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetConClctFailResnPagingOut
 */
export interface GetConClctFailResnPagingOut {
    /**
     * 
     * @type {string}
     * @memberof GetConClctFailResnPagingOut
     */
    'conFailResn'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetConClctFailResnPagingOut
     */
    'dtlCtn'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetConClctFailResnPagingOut
     */
    'ptbId'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetConClctFailResnPagingOut
     */
    'regDy'?: string;
}

