/* tslint:disable */
/* eslint-disable */
/**
 * Rsquare Manage Server
 * Api Document
 *
 * The version of the OpenAPI document: V22.20.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetScrapOut
 */
export interface GetScrapOut {
    /**
     * 
     * @type {string}
     * @memberof GetScrapOut
     */
    'basicYn'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetScrapOut
     */
    'createDt': string;
    /**
     * 
     * @type {string}
     * @memberof GetScrapOut
     */
    'createUserName'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetScrapOut
     */
    'ownUserId': string;
    /**
     * 
     * @type {string}
     * @memberof GetScrapOut
     */
    'ownUserName': string;
    /**
     * 
     * @type {string}
     * @memberof GetScrapOut
     */
    'publicYn': string;
    /**
     * 
     * @type {string}
     * @memberof GetScrapOut
     */
    'scrapId': string;
    /**
     * 
     * @type {string}
     * @memberof GetScrapOut
     */
    'scrapItemTypeCd': string;
    /**
     * 
     * @type {string}
     * @memberof GetScrapOut
     */
    'scrapItemTypeName': string;
    /**
     * 
     * @type {string}
     * @memberof GetScrapOut
     */
    'scrapName': string;
    /**
     * 
     * @type {string}
     * @memberof GetScrapOut
     */
    'scrapTgtRelCd'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetScrapOut
     */
    'scrapTgtRelName'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetScrapOut
     */
    'scrapType'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetScrapOut
     */
    'tgtId'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetScrapOut
     */
    'tgtName'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetScrapOut
     */
    'updateDt'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetScrapOut
     */
    'updateUserName'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetScrapOut
     */
    'useYn'?: string;
}

