/* tslint:disable */
/* eslint-disable */
/**
 * Rsquare Manage Server
 * Api Document
 *
 * The version of the OpenAPI document: V22.20.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetPhtForBldPrdSearchCardOut
 */
export interface GetPhtForBldPrdSearchCardOut {
    /**
     * 
     * @type {string}
     * @memberof GetPhtForBldPrdSearchCardOut
     */
    'bldId': string;
    /**
     * 
     * @type {string}
     * @memberof GetPhtForBldPrdSearchCardOut
     */
    'phtId': string;
    /**
     * 
     * @type {string}
     * @memberof GetPhtForBldPrdSearchCardOut
     */
    'phtLcl'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetPhtForBldPrdSearchCardOut
     */
    'phtLclCd'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetPhtForBldPrdSearchCardOut
     */
    'phtUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetPhtForBldPrdSearchCardOut
     */
    'prdId': string;
}

