/* tslint:disable */
/* eslint-disable */
/**
 * Rsquare Manage Server
 * Api Document
 *
 * The version of the OpenAPI document: V22.20.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetRegnStatOut
 */
export interface GetRegnStatOut {
    /**
     * 
     * @type {string}
     * @memberof GetRegnStatOut
     */
    'cbd': string;
    /**
     * 
     * @type {string}
     * @memberof GetRegnStatOut
     */
    'dmc': string;
    /**
     * 
     * @type {string}
     * @memberof GetRegnStatOut
     */
    'exp': string;
    /**
     * 
     * @type {string}
     * @memberof GetRegnStatOut
     */
    'gbd': string;
    /**
     * 
     * @type {string}
     * @memberof GetRegnStatOut
     */
    'ptv': string;
    /**
     * 
     * @type {string}
     * @memberof GetRegnStatOut
     */
    'sbd': string;
    /**
     * 
     * @type {string}
     * @memberof GetRegnStatOut
     */
    'ybd': string;
}

