/* tslint:disable */
/* eslint-disable */
/**
 * Rsquare Manage Server
 * Api Document
 *
 * The version of the OpenAPI document: V22.20.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetContrDealListOut
 */
export interface GetContrDealListOut {
    /**
     * 
     * @type {string}
     * @memberof GetContrDealListOut
     */
    'cln'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetContrDealListOut
     */
    'dealId': string;
    /**
     * 
     * @type {string}
     * @memberof GetContrDealListOut
     */
    'dealName'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetContrDealListOut
     */
    'dealType'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetContrDealListOut
     */
    'taskCfCd'?: string;
}

