/* tslint:disable */
/* eslint-disable */
/**
 * Rsquare Manage Server
 * Api Document
 *
 * The version of the OpenAPI document: V22.20.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetAllInbListOut
 */
export interface GetAllInbListOut {
    /**
     * 
     * @type {string}
     * @memberof GetAllInbListOut
     */
    'coName'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAllInbListOut
     */
    'cusName'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAllInbListOut
     */
    'dealYn'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAllInbListOut
     */
    'inbType'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAllInbListOut
     */
    'inbTypeCd'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAllInbListOut
     */
    'procDy'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAllInbListOut
     */
    'procStat'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAllInbListOut
     */
    'procStatCd'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAllInbListOut
     */
    'procUser'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAllInbListOut
     */
    'procUserId'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAllInbListOut
     */
    'qusTypeCd'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAllInbListOut
     */
    'qusTypeName'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAllInbListOut
     */
    'regDt'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAllInbListOut
     */
    'taskId': string;
}

