/* tslint:disable */
/* eslint-disable */
/**
 * Rsquare Manage Server
 * Api Document
 *
 * The version of the OpenAPI document: V22.20.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { GetIntCusInfoListOut } from './get-int-cus-info-list-out';

/**
 * 
 * @export
 * @interface GetIntClnCusListOut
 */
export interface GetIntClnCusListOut {
    /**
     * 
     * @type {string}
     * @memberof GetIntClnCusListOut
     */
    'clnId': string;
    /**
     * 
     * @type {string}
     * @memberof GetIntClnCusListOut
     */
    'clnName'?: string;
    /**
     * 
     * @type {Array<GetIntCusInfoListOut>}
     * @memberof GetIntClnCusListOut
     */
    'cus': Array<GetIntCusInfoListOut>;
    /**
     * 
     * @type {string}
     * @memberof GetIntClnCusListOut
     */
    'ksic'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetIntClnCusListOut
     */
    'mainAddr'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetIntClnCusListOut
     */
    'projId': string;
}

