/* tslint:disable */
/* eslint-disable */
/**
 * Rsquare Manage Server
 * Api Document
 *
 * The version of the OpenAPI document: V22.20.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetSmsReqWaitOut
 */
export interface GetSmsReqWaitOut {
    /**
     * 
     * @type {string}
     * @memberof GetSmsReqWaitOut
     */
    'createDt': string;
    /**
     * 
     * @type {string}
     * @memberof GetSmsReqWaitOut
     */
    'createUserName': string;
    /**
     * 
     * @type {number}
     * @memberof GetSmsReqWaitOut
     */
    'parSeq': number;
    /**
     * 
     * @type {number}
     * @memberof GetSmsReqWaitOut
     */
    'sendCnt': number;
    /**
     * 
     * @type {string}
     * @memberof GetSmsReqWaitOut
     */
    'senderTelNum': string;
    /**
     * 
     * @type {string}
     * @memberof GetSmsReqWaitOut
     */
    'smsCtn': string;
    /**
     * 
     * @type {string}
     * @memberof GetSmsReqWaitOut
     */
    'smsSbj': string;
    /**
     * 
     * @type {string}
     * @memberof GetSmsReqWaitOut
     */
    'smsTmplId': string;
    /**
     * 
     * @type {string}
     * @memberof GetSmsReqWaitOut
     */
    'umsProcStatName': string;
}

