/* tslint:disable */
/* eslint-disable */
/**
 * Rsquare Manage Server
 * Api Document
 *
 * The version of the OpenAPI document: V22.20.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetBrdLineOut
 */
export interface GetBrdLineOut {
    /**
     * 
     * @type {string}
     * @memberof GetBrdLineOut
     */
    'brdId': string;
    /**
     * 
     * @type {string}
     * @memberof GetBrdLineOut
     */
    'brdLineId': string;
    /**
     * 
     * @type {string}
     * @memberof GetBrdLineOut
     */
    'brdName': string;
    /**
     * 
     * @type {string}
     * @memberof GetBrdLineOut
     */
    'lineName': string;
}

