/* tslint:disable */
/* eslint-disable */
/**
 * Rsquare Manage Server
 * Api Document
 *
 * The version of the OpenAPI document: V22.20.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetSmsTmplOut
 */
export interface GetSmsTmplOut {
    /**
     * 
     * @type {string}
     * @memberof GetSmsTmplOut
     */
    'createDt'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetSmsTmplOut
     */
    'createUserName'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetSmsTmplOut
     */
    'smsCtn'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetSmsTmplOut
     */
    'smsSbj'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetSmsTmplOut
     */
    'smsTmplId': string;
    /**
     * 
     * @type {string}
     * @memberof GetSmsTmplOut
     */
    'smsTmplTypeCd': string;
    /**
     * 
     * @type {string}
     * @memberof GetSmsTmplOut
     */
    'smsTmplTypeCdName': string;
    /**
     * 
     * @type {string}
     * @memberof GetSmsTmplOut
     */
    'tmplName': string;
    /**
     * 
     * @type {string}
     * @memberof GetSmsTmplOut
     */
    'updateDt'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetSmsTmplOut
     */
    'updateUserName'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetSmsTmplOut
     */
    'useYn': string;
}

