/* tslint:disable */
/* eslint-disable */
/**
 * Rsquare Manage Server
 * Api Document
 *
 * The version of the OpenAPI document: V22.20.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetContrEtcClnCusListOut
 */
export interface GetContrEtcClnCusListOut {
    /**
     * 
     * @type {string}
     * @memberof GetContrEtcClnCusListOut
     */
    'addr'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetContrEtcClnCusListOut
     */
    'bizRegistNum'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetContrEtcClnCusListOut
     */
    'ceoName'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetContrEtcClnCusListOut
     */
    'clnName'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetContrEtcClnCusListOut
     */
    'conNum'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetContrEtcClnCusListOut
     */
    'contrClnRelType'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetContrEtcClnCusListOut
     */
    'contrClnRelTypeCd'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetContrEtcClnCusListOut
     */
    'contrCusRelType'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetContrEtcClnCusListOut
     */
    'contrCusRelTypeCd'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetContrEtcClnCusListOut
     */
    'cusName'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetContrEtcClnCusListOut
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetContrEtcClnCusListOut
     */
    'relClnId'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetContrEtcClnCusListOut
     */
    'relCusId'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetContrEtcClnCusListOut
     */
    'taxPtb'?: string;
}

