/* tslint:disable */
/* eslint-disable */
/**
 * Rsquare Manage Server
 * Api Document
 *
 * The version of the OpenAPI document: V22.20.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetPrdForBldCardOut
 */
export interface GetPrdForBldCardOut {
    /**
     * 
     * @type {number}
     * @memberof GetPrdForBldCardOut
     */
    'dpstAmt'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetPrdForBldCardOut
     */
    'flrNum'?: number;
    /**
     * 
     * @type {string}
     * @memberof GetPrdForBldCardOut
     */
    'incldSchYn': string;
    /**
     * 
     * @type {number}
     * @memberof GetPrdForBldCardOut
     */
    'maintAmt'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetPrdForBldCardOut
     */
    'nlaPy'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetPrdForBldCardOut
     */
    'nocAmt'?: number;
    /**
     * 
     * @type {string}
     * @memberof GetPrdForBldCardOut
     */
    'phtYn': string;
    /**
     * 
     * @type {string}
     * @memberof GetPrdForBldCardOut
     */
    'prdId': string;
    /**
     * 
     * @type {string}
     * @memberof GetPrdForBldCardOut
     */
    'prsScrapYn': string;
    /**
     * 
     * @type {string}
     * @memberof GetPrdForBldCardOut
     */
    'publicScrapYn': string;
    /**
     * 
     * @type {string}
     * @memberof GetPrdForBldCardOut
     */
    'shofiYn': string;
    /**
     * 
     * @type {string}
     * @memberof GetPrdForBldCardOut
     */
    'unitDispName'?: string;
}

