/* tslint:disable */
/* eslint-disable */
/**
 * Rsquare Manage Server
 * Api Document
 *
 * The version of the OpenAPI document: V22.20.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { GetCusConOut } from './get-cus-con-out';

/**
 * 
 * @export
 * @interface GetCcalClnCusWithConOut
 */
export interface GetCcalClnCusWithConOut {
    /**
     * 
     * @type {string}
     * @memberof GetCcalClnCusWithConOut
     */
    'bselInChrgYn': string;
    /**
     * 
     * @type {string}
     * @memberof GetCcalClnCusWithConOut
     */
    'clnCusRelType'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetCcalClnCusWithConOut
     */
    'clnCusRelTypeCd'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetCcalClnCusWithConOut
     */
    'conTgtType': string;
    /**
     * 
     * @type {Array<GetCusConOut>}
     * @memberof GetCcalClnCusWithConOut
     */
    'cons': Array<GetCusConOut>;
    /**
     * 
     * @type {string}
     * @memberof GetCcalClnCusWithConOut
     */
    'cusId': string;
    /**
     * 
     * @type {string}
     * @memberof GetCcalClnCusWithConOut
     */
    'cusName': string;
    /**
     * 
     * @type {string}
     * @memberof GetCcalClnCusWithConOut
     */
    'etcCtn': string;
    /**
     * 
     * @type {string}
     * @memberof GetCcalClnCusWithConOut
     */
    'furInChrgYn': string;
    /**
     * 
     * @type {string}
     * @memberof GetCcalClnCusWithConOut
     */
    'intInChrgYn': string;
    /**
     * 
     * @type {string}
     * @memberof GetCcalClnCusWithConOut
     */
    'jobType'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetCcalClnCusWithConOut
     */
    'jobTypeCd'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetCcalClnCusWithConOut
     */
    'leaseInChrgYn': string;
    /**
     * 
     * @type {string}
     * @memberof GetCcalClnCusWithConOut
     */
    'lwhLeaseInChrgYn': string;
    /**
     * 
     * @type {string}
     * @memberof GetCcalClnCusWithConOut
     */
    'lwhRentInChrgYn': string;
    /**
     * 
     * @type {string}
     * @memberof GetCcalClnCusWithConOut
     */
    'mptbYn': string;
    /**
     * 
     * @type {string}
     * @memberof GetCcalClnCusWithConOut
     */
    'rankType'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetCcalClnCusWithConOut
     */
    'rankTypeCd'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetCcalClnCusWithConOut
     */
    'rentInChrgYn': string;
    /**
     * 
     * @type {string}
     * @memberof GetCcalClnCusWithConOut
     */
    'retailLeaseInChrgYn'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetCcalClnCusWithConOut
     */
    'retailRentInChrgYn'?: string;
}

