/* tslint:disable */
/* eslint-disable */
/**
 * Rsquare Manage Server
 * Api Document
 *
 * The version of the OpenAPI document: V22.20.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ObjBldMst
 */
export interface ObjBldMst {
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'acSplyTypeCd': string;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'allDayOpenTypeCd': string;
    /**
     * 
     * @type {number}
     * @memberof ObjBldMst
     */
    'blaM2'?: number;
    /**
     * 
     * @type {number}
     * @memberof ObjBldMst
     */
    'blaPy'?: number;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'bldDrcnCd': string;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'bldId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'bldKindName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'bldLastCallDt'?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'bldLastCallPtbId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'bldName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'bldPhtCollectExptCd': string;
    /**
     * 
     * @type {number}
     * @memberof ObjBldMst
     */
    'bsmtCnt'?: number;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'cityDvpDistYn': string;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'cmplCostrDueDy'?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'cmplCostrYear'?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'collectCycleCd': string;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'collectCycleResnCd': string;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'costrStatCd': string;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'createDt'?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'createUserId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'dsgnParkCd': string;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'elvStatCd': string;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'etcRstaYn': string;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'exclBldYn'?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'exclRetailYn'?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'exteriorCaptPsblYn'?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'externalDispResnCtn'?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'externalDispYn': string;
    /**
     * 
     * @type {number}
     * @memberof ObjBldMst
     */
    'faRate'?: number;
    /**
     * 
     * @type {number}
     * @memberof ObjBldMst
     */
    'flrCnt'?: number;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'freeParkBaseCd': string;
    /**
     * 
     * @type {number}
     * @memberof ObjBldMst
     */
    'freeParkCnt'?: number;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'freeParkDtl'?: string;
    /**
     * 
     * @type {number}
     * @memberof ObjBldMst
     */
    'frghtElvCnt'?: number;
    /**
     * 
     * @type {number}
     * @memberof ObjBldMst
     */
    'graM2'?: number;
    /**
     * 
     * @type {number}
     * @memberof ObjBldMst
     */
    'graPy'?: number;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'hdyOpenTypeCd': string;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'heatSplyTypeCd': string;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'houseOfficeYn': string;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'inDivWcYn': string;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'inPublicWcYn': string;
    /**
     * 
     * @type {number}
     * @memberof ObjBldMst
     */
    'lat'?: number;
    /**
     * 
     * @type {number}
     * @memberof ObjBldMst
     */
    'lng'?: number;
    /**
     * 
     * @type {number}
     * @memberof ObjBldMst
     */
    'minPartnNlaM2'?: number;
    /**
     * 
     * @type {number}
     * @memberof ObjBldMst
     */
    'minPartnNlaPy'?: number;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'outEdivWcYn': string;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'outEpubWcYn': string;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'outId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'outMdivWcYn': string;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'outMngCd'?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'outMpubWcYn': string;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'paidParkBaseCd': string;
    /**
     * 
     * @type {number}
     * @memberof ObjBldMst
     */
    'paidParkCnt'?: number;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'paidParkDtl'?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'paroBldChkNeedYn': string;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'paroTypeCd': string;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'partnRentCd': string;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'pkltTypeCd': string;
    /**
     * 
     * @type {number}
     * @memberof ObjBldMst
     */
    'plaM2'?: number;
    /**
     * 
     * @type {number}
     * @memberof ObjBldMst
     */
    'plaPy'?: number;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'prdChkDy'?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'prdChkPtbId'?: string;
    /**
     * 
     * @type {number}
     * @memberof ObjBldMst
     */
    'prdCnt'?: number;
    /**
     * 
     * @type {number}
     * @memberof ObjBldMst
     */
    'publicElvCnt'?: number;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'rentCfCd': string;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'rgdnRstaYn': string;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'rmdlYear'?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'rmdlYn': string;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'roadNameAddr'?: string;
    /**
     * 
     * @type {number}
     * @memberof ObjBldMst
     */
    'seq'?: number;
    /**
     * 
     * @type {number}
     * @memberof ObjBldMst
     */
    'stdFlr'?: number;
    /**
     * 
     * @type {number}
     * @memberof ObjBldMst
     */
    'stdFlrDpstAmt': number;
    /**
     * 
     * @type {number}
     * @memberof ObjBldMst
     */
    'stdFlrFoMonth': number;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'stdFlrFoMtnFeeIncldYn': string;
    /**
     * 
     * @type {number}
     * @memberof ObjBldMst
     */
    'stdFlrGlaM2'?: number;
    /**
     * 
     * @type {number}
     * @memberof ObjBldMst
     */
    'stdFlrGlaPy'?: number;
    /**
     * 
     * @type {number}
     * @memberof ObjBldMst
     */
    'stdFlrMtnFeeAmt': number;
    /**
     * 
     * @type {number}
     * @memberof ObjBldMst
     */
    'stdFlrNlaM2'?: number;
    /**
     * 
     * @type {number}
     * @memberof ObjBldMst
     */
    'stdFlrNlaPy'?: number;
    /**
     * 
     * @type {number}
     * @memberof ObjBldMst
     */
    'stdFlrNoc': number;
    /**
     * 
     * @type {number}
     * @memberof ObjBldMst
     */
    'stdFlrRentAmt': number;
    /**
     * 
     * @type {number}
     * @memberof ObjBldMst
     */
    'stdFlrRfMonth': number;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'stdFlrRfMtnFeeIncldYn': string;
    /**
     * 
     * @type {number}
     * @memberof ObjBldMst
     */
    'stdFlrTi': number;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'substaId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'tmAsgmtDlyCd': string;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'tmAsgmtDlyResnCd': string;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'tracRstaYn': string;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'updateDt'?: string;
    /**
     * 
     * @type {string}
     * @memberof ObjBldMst
     */
    'updateUserId'?: string;
}

