/* tslint:disable */
/* eslint-disable */
/**
 * Rsquare Manage Server
 * Api Document
 *
 * The version of the OpenAPI document: V22.20.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { GetRoleApiOut } from './get-role-api-out';

/**
 * 
 * @export
 * @interface PagingGetRoleApiOut
 */
export interface PagingGetRoleApiOut {
    /**
     * 
     * @type {boolean}
     * @memberof PagingGetRoleApiOut
     */
    'bfirstPage': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PagingGetRoleApiOut
     */
    'blastPage': boolean;
    /**
     * 
     * @type {number}
     * @memberof PagingGetRoleApiOut
     */
    'endRow': number;
    /**
     * 
     * @type {number}
     * @memberof PagingGetRoleApiOut
     */
    'firstPageNum': number;
    /**
     * 
     * @type {boolean}
     * @memberof PagingGetRoleApiOut
     */
    'hasNextPage': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PagingGetRoleApiOut
     */
    'hasPreviousPage': boolean;
    /**
     * 
     * @type {number}
     * @memberof PagingGetRoleApiOut
     */
    'lastPageNum': number;
    /**
     * 
     * @type {Array<GetRoleApiOut>}
     * @memberof PagingGetRoleApiOut
     */
    'list': Array<GetRoleApiOut>;
    /**
     * 
     * @type {string}
     * @memberof PagingGetRoleApiOut
     */
    'orderBy'?: string;
    /**
     * 
     * @type {number}
     * @memberof PagingGetRoleApiOut
     */
    'pageNum': number;
    /**
     * 
     * @type {number}
     * @memberof PagingGetRoleApiOut
     */
    'pageSize': number;
    /**
     * 
     * @type {number}
     * @memberof PagingGetRoleApiOut
     */
    'pages': number;
    /**
     * 
     * @type {number}
     * @memberof PagingGetRoleApiOut
     */
    'startRow': number;
    /**
     * 
     * @type {number}
     * @memberof PagingGetRoleApiOut
     */
    'total': number;
}

