/* tslint:disable */
/* eslint-disable */
/**
 * Rsquare Manage Server
 * Api Document
 *
 * The version of the OpenAPI document: V22.20.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PatchLeaseIn
 */
export interface PatchLeaseIn {
    /**
     * 
     * @type {string}
     * @memberof PatchLeaseIn
     */
    'workId'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchLeaseIn
     */
    'taskId'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchLeaseIn
     */
    'taskName'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchLeaseIn
     */
    'dealStatCd'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchLeaseIn
     */
    'mptb'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof PatchLeaseIn
     */
    'sptbs'?: Array<string>;
}

