/* tslint:disable */
/* eslint-disable */
/**
 * Rsquare Manage Server
 * Api Document
 *
 * The version of the OpenAPI document: V22.20.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PatchLwhUnitIn
 */
export interface PatchLwhUnitIn {
    /**
     * 
     * @type {string}
     * @memberof PatchLwhUnitIn
     */
    'lwhId': string;
    /**
     * 
     * @type {string}
     * @memberof PatchLwhUnitIn
     */
    'unitLwhId': string;
    /**
     * 
     * @type {string}
     * @memberof PatchLwhUnitIn
     */
    'useYn'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchLwhUnitIn
     */
    'dgName'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchLwhUnitIn
     */
    'dgUseYn'?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchLwhUnitIn
     */
    'glaPy'?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchLwhUnitIn
     */
    'glaM2'?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchLwhUnitIn
     */
    'nlaPy'?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchLwhUnitIn
     */
    'nlaM2'?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchLwhUnitIn
     */
    'exclRate'?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchLwhUnitIn
     */
    'unitName'?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchLwhUnitIn
     */
    'flrHeightM'?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchLwhUnitIn
     */
    'flrStrKnm2'?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchLwhUnitIn
     */
    'flrUseTypeCd'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchLwhUnitIn
     */
    'storeTypeCd'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchLwhUnitIn
     */
    'convTypeCdList'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchLwhUnitIn
     */
    'updateUserId'?: string;
}

