/* tslint:disable */
/* eslint-disable */
/**
 * Rsquare Manage Server
 * Api Document
 *
 * The version of the OpenAPI document: V22.20.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PatchSavingInfoIn
 */
export interface PatchSavingInfoIn {
    /**
     * 
     * @type {number}
     * @memberof PatchSavingInfoIn
     */
    'savingAmt'?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchSavingInfoIn
     */
    'savingDueDy'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchSavingInfoIn
     */
    'taxinvDueDy'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchSavingInfoIn
     */
    'taxinvIssYn'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchSavingInfoIn
     */
    'taxinvIssDy'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchSavingInfoIn
     */
    'savingYn'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchSavingInfoIn
     */
    'savingDy'?: string;
}

