/* tslint:disable */
/* eslint-disable */
/**
 * Rsquare Manage Server
 * Api Document
 *
 * The version of the OpenAPI document: V22.20.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PatchPrdForBldScreenModalIn
 */
export interface PatchPrdForBldScreenModalIn {
    /**
     * 
     * @type {string}
     * @memberof PatchPrdForBldScreenModalIn
     */
    'prdId'?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchPrdForBldScreenModalIn
     */
    'seq'?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchPrdForBldScreenModalIn
     */
    'bldId'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchPrdForBldScreenModalIn
     */
    'unitId'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchPrdForBldScreenModalIn
     */
    'useYn'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchPrdForBldScreenModalIn
     */
    'dispStartDy'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchPrdForBldScreenModalIn
     */
    'dispEndDy'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchPrdForBldScreenModalIn
     */
    'prdTrStatCd'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchPrdForBldScreenModalIn
     */
    'dispYn'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchPrdForBldScreenModalIn
     */
    'contrImmYn'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchPrdForBldScreenModalIn
     */
    'lessorAgrmYn'?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchPrdForBldScreenModalIn
     */
    'dpstAmt'?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchPrdForBldScreenModalIn
     */
    'rentAmt'?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchPrdForBldScreenModalIn
     */
    'mtnFeeAmt'?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchPrdForBldScreenModalIn
     */
    'mtnFeeStatCd'?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchPrdForBldScreenModalIn
     */
    'nocAmt'?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchPrdForBldScreenModalIn
     */
    'eqpCostAmt'?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchPrdForBldScreenModalIn
     */
    'eqpCtn'?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchPrdForBldScreenModalIn
     */
    'freeParkCnt'?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchPrdForBldScreenModalIn
     */
    'parkExpl'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchPrdForBldScreenModalIn
     */
    'etcCtn'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchPrdForBldScreenModalIn
     */
    'mvinStatCd'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchPrdForBldScreenModalIn
     */
    'mvinPslbYm'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchPrdForBldScreenModalIn
     */
    'intYn'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchPrdForBldScreenModalIn
     */
    'rmPhtYn'?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchPrdForBldScreenModalIn
     */
    'intRomCnt'?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchPrdForBldScreenModalIn
     */
    'lodbYn'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchPrdForBldScreenModalIn
     */
    'prdType'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchPrdForBldScreenModalIn
     */
    'freeParkTimeCd'?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchPrdForBldScreenModalIn
     */
    'premiumAmt'?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchPrdForBldScreenModalIn
     */
    'premiumYn'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchPrdForBldScreenModalIn
     */
    'industryLargeCd'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchPrdForBldScreenModalIn
     */
    'industryMiddleCd'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchPrdForBldScreenModalIn
     */
    'tenantIndustryDtl'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchPrdForBldScreenModalIn
     */
    'rstType'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchPrdForBldScreenModalIn
     */
    'acSplyPsblCd'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchPrdForBldScreenModalIn
     */
    'heatSplyPsblCd'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchPrdForBldScreenModalIn
     */
    'areaPartnPsblCd'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchPrdForBldScreenModalIn
     */
    'mvinStartTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchPrdForBldScreenModalIn
     */
    'mvinEndTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchPrdForBldScreenModalIn
     */
    'signBoardPsblCd'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchPrdForBldScreenModalIn
     */
    'checkoutType'?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchPrdForBldScreenModalIn
     */
    'tenantName'?: string;
}

