/* tslint:disable */
/* eslint-disable */
/**
 * Rsquare Manage Server
 * Api Document
 *
 * The version of the OpenAPI document: V22.20.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PostContIn
 */
export interface PostContIn {
    /**
     * 
     * @type {string}
     * @memberof PostContIn
     */
    'contCfCd': string;
    /**
     * 
     * @type {string}
     * @memberof PostContIn
     */
    'sbj': string;
    /**
     * 
     * @type {string}
     * @memberof PostContIn
     */
    'contCtn': string;
    /**
     * 
     * @type {string}
     * @memberof PostContIn
     */
    'createDt'?: string;
    /**
     * 
     * @type {string}
     * @memberof PostContIn
     */
    'createUserId'?: string;
}

