/* tslint:disable */
/* eslint-disable */
/**
 * Rsquare Manage Server
 * Api Document
 *
 * The version of the OpenAPI document: V22.20.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PostComRoleIn
 */
export interface PostComRoleIn {
    /**
     * 
     * @type {string}
     * @memberof PostComRoleIn
     */
    'roleName': string;
    /**
     * 
     * @type {string}
     * @memberof PostComRoleIn
     */
    'roleId'?: string;
    /**
     * 
     * @type {string}
     * @memberof PostComRoleIn
     */
    'expl'?: string;
    /**
     * 
     * @type {string}
     * @memberof PostComRoleIn
     */
    'createUserId'?: string;
    /**
     * 
     * @type {string}
     * @memberof PostComRoleIn
     */
    'createDt'?: string;
}

