/* tslint:disable */
/* eslint-disable */
/**
 * Rsquare Manage Server
 * Api Document
 *
 * The version of the OpenAPI document: V22.20.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PostFeeInfoIn
 */
export interface PostFeeInfoIn {
    /**
     * 
     * @type {string}
     * @memberof PostFeeInfoIn
     */
    'clnId'?: string;
    /**
     * 
     * @type {string}
     * @memberof PostFeeInfoIn
     */
    'focYn'?: string;
    /**
     * 
     * @type {string}
     * @memberof PostFeeInfoIn
     */
    'feeCalcMethodCd'?: string;
    /**
     * 
     * @type {string}
     * @memberof PostFeeInfoIn
     */
    'feePayWayCd'?: string;
    /**
     * 
     * @type {number}
     * @memberof PostFeeInfoIn
     */
    'payiiCnt'?: number;
    /**
     * 
     * @type {string}
     * @memberof PostFeeInfoIn
     */
    'taxinvIssStatCd'?: string;
    /**
     * 
     * @type {string}
     * @memberof PostFeeInfoIn
     */
    'feeCalcTypeCd'?: string;
    /**
     * 
     * @type {number}
     * @memberof PostFeeInfoIn
     */
    'feeRate'?: number;
    /**
     * 
     * @type {string}
     * @memberof PostFeeInfoIn
     */
    'vatIncldYn'?: string;
    /**
     * 
     * @type {number}
     * @memberof PostFeeInfoIn
     */
    'entryAmt'?: number;
    /**
     * 
     * @type {number}
     * @memberof PostFeeInfoIn
     */
    'premiumFeeAmt'?: number;
    /**
     * 
     * @type {number}
     * @memberof PostFeeInfoIn
     */
    'vatTotalFeeAmt'?: number;
}

