/* tslint:disable */
/* eslint-disable */
/**
 * Rsquare Manage Server
 * Api Document
 *
 * The version of the OpenAPI document: V22.20.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SaveLmClnExclBldTaskIn
 */
export interface SaveLmClnExclBldTaskIn {
    /**
     * 
     * @type {string}
     * @memberof SaveLmClnExclBldTaskIn
     */
    'clnId'?: string;
    /**
     * 
     * @type {string}
     * @memberof SaveLmClnExclBldTaskIn
     */
    'bldId'?: string;
    /**
     * 
     * @type {string}
     * @memberof SaveLmClnExclBldTaskIn
     */
    'taskRegDy'?: string;
    /**
     * 
     * @type {string}
     * @memberof SaveLmClnExclBldTaskIn
     */
    'dtlCtn'?: string;
}

