/* tslint:disable */
/* eslint-disable */
/**
 * Rsquare Manage Server
 * Api Document
 *
 * The version of the OpenAPI document: V22.20.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SelectLwhPrdListForScreenOut
 */
export interface SelectLwhPrdListForScreenOut {
    /**
     * 
     * @type {string}
     * @memberof SelectLwhPrdListForScreenOut
     */
    'createDt'?: string;
    /**
     * 
     * @type {string}
     * @memberof SelectLwhPrdListForScreenOut
     */
    'createUserId'?: string;
    /**
     * 
     * @type {string}
     * @memberof SelectLwhPrdListForScreenOut
     */
    'createUserName'?: string;
    /**
     * 
     * @type {string}
     * @memberof SelectLwhPrdListForScreenOut
     */
    'dispEndDy'?: string;
    /**
     * 
     * @type {string}
     * @memberof SelectLwhPrdListForScreenOut
     */
    'dispStartDy'?: string;
    /**
     * 
     * @type {string}
     * @memberof SelectLwhPrdListForScreenOut
     */
    'dispYn'?: string;
    /**
     * 
     * @type {number}
     * @memberof SelectLwhPrdListForScreenOut
     */
    'dpstAmt': number;
    /**
     * 
     * @type {string}
     * @memberof SelectLwhPrdListForScreenOut
     */
    'etcCtn'?: string;
    /**
     * 
     * @type {number}
     * @memberof SelectLwhPrdListForScreenOut
     */
    'exclRate': number;
    /**
     * 
     * @type {string}
     * @memberof SelectLwhPrdListForScreenOut
     */
    'flrUseTypeCd'?: string;
    /**
     * 
     * @type {string}
     * @memberof SelectLwhPrdListForScreenOut
     */
    'flrUseTypeName'?: string;
    /**
     * 
     * @type {string}
     * @memberof SelectLwhPrdListForScreenOut
     */
    'freeParkCnt'?: string;
    /**
     * 
     * @type {number}
     * @memberof SelectLwhPrdListForScreenOut
     */
    'glaM2': number;
    /**
     * 
     * @type {number}
     * @memberof SelectLwhPrdListForScreenOut
     */
    'glaPy': number;
    /**
     * 
     * @type {string}
     * @memberof SelectLwhPrdListForScreenOut
     */
    'lwhId': string;
    /**
     * 
     * @type {string}
     * @memberof SelectLwhPrdListForScreenOut
     */
    'lwhPrdTrStatCd'?: string;
    /**
     * 
     * @type {number}
     * @memberof SelectLwhPrdListForScreenOut
     */
    'mtnFeeAmt': number;
    /**
     * 
     * @type {string}
     * @memberof SelectLwhPrdListForScreenOut
     */
    'mtnFeeStatCd'?: string;
    /**
     * 
     * @type {string}
     * @memberof SelectLwhPrdListForScreenOut
     */
    'mtnFeeStatName'?: string;
    /**
     * 
     * @type {string}
     * @memberof SelectLwhPrdListForScreenOut
     */
    'mvinPslbYm'?: string;
    /**
     * 
     * @type {string}
     * @memberof SelectLwhPrdListForScreenOut
     */
    'mvinStatCd'?: string;
    /**
     * 
     * @type {string}
     * @memberof SelectLwhPrdListForScreenOut
     */
    'mvinStatName'?: string;
    /**
     * 
     * @type {number}
     * @memberof SelectLwhPrdListForScreenOut
     */
    'nlaM2': number;
    /**
     * 
     * @type {number}
     * @memberof SelectLwhPrdListForScreenOut
     */
    'nlaPy': number;
    /**
     * 
     * @type {string}
     * @memberof SelectLwhPrdListForScreenOut
     */
    'parkExpl'?: string;
    /**
     * 
     * @type {number}
     * @memberof SelectLwhPrdListForScreenOut
     */
    'phtCnt'?: number;
    /**
     * 
     * @type {number}
     * @memberof SelectLwhPrdListForScreenOut
     */
    'prdCnt'?: number;
    /**
     * 
     * @type {string}
     * @memberof SelectLwhPrdListForScreenOut
     */
    'prdLwhId': string;
    /**
     * 
     * @type {string}
     * @memberof SelectLwhPrdListForScreenOut
     */
    'prdPhtgFailCorrCd'?: string;
    /**
     * 
     * @type {string}
     * @memberof SelectLwhPrdListForScreenOut
     */
    'prdPhtgFailCorrName'?: string;
    /**
     * 
     * @type {string}
     * @memberof SelectLwhPrdListForScreenOut
     */
    'prdPhtgFailCtn'?: string;
    /**
     * 
     * @type {string}
     * @memberof SelectLwhPrdListForScreenOut
     */
    'prdPhtgFailDy'?: string;
    /**
     * 
     * @type {string}
     * @memberof SelectLwhPrdListForScreenOut
     */
    'prdPhtgFailPtbId'?: string;
    /**
     * 
     * @type {string}
     * @memberof SelectLwhPrdListForScreenOut
     */
    'prdPhtgFailPtbName'?: string;
    /**
     * 
     * @type {string}
     * @memberof SelectLwhPrdListForScreenOut
     */
    'prdPhtgStatCd'?: string;
    /**
     * 
     * @type {string}
     * @memberof SelectLwhPrdListForScreenOut
     */
    'prdPhtgStatName'?: string;
    /**
     * 
     * @type {string}
     * @memberof SelectLwhPrdListForScreenOut
     */
    'prdTrStatName'?: string;
    /**
     * 
     * @type {string}
     * @memberof SelectLwhPrdListForScreenOut
     */
    'prsScrapYn': string;
    /**
     * 
     * @type {string}
     * @memberof SelectLwhPrdListForScreenOut
     */
    'publicScrapYn': string;
    /**
     * 
     * @type {number}
     * @memberof SelectLwhPrdListForScreenOut
     */
    'rentAmt': number;
    /**
     * 
     * @type {string}
     * @memberof SelectLwhPrdListForScreenOut
     */
    'stdFlrMatchYn'?: string;
    /**
     * 
     * @type {string}
     * @memberof SelectLwhPrdListForScreenOut
     */
    'storeTypeCd'?: string;
    /**
     * 
     * @type {string}
     * @memberof SelectLwhPrdListForScreenOut
     */
    'storeTypeName'?: string;
    /**
     * 
     * @type {number}
     * @memberof SelectLwhPrdListForScreenOut
     */
    'tipCnt'?: number;
    /**
     * 
     * @type {string}
     * @memberof SelectLwhPrdListForScreenOut
     */
    'unitCfCd'?: string;
    /**
     * 
     * @type {string}
     * @memberof SelectLwhPrdListForScreenOut
     */
    'unitCfName'?: string;
    /**
     * 
     * @type {string}
     * @memberof SelectLwhPrdListForScreenOut
     */
    'unitDispName'?: string;
    /**
     * 
     * @type {string}
     * @memberof SelectLwhPrdListForScreenOut
     */
    'unitLwhId': string;
    /**
     * 
     * @type {string}
     * @memberof SelectLwhPrdListForScreenOut
     */
    'updateDt'?: string;
    /**
     * 
     * @type {string}
     * @memberof SelectLwhPrdListForScreenOut
     */
    'updateUserId'?: string;
    /**
     * 
     * @type {string}
     * @memberof SelectLwhPrdListForScreenOut
     */
    'updateUserName'?: string;
    /**
     * 
     * @type {string}
     * @memberof SelectLwhPrdListForScreenOut
     */
    'useYn'?: string;
    /**
     * 
     * @type {string}
     * @memberof SelectLwhPrdListForScreenOut
     */
    'utilExpenseStatCd'?: string;
}

