/* tslint:disable */
/* eslint-disable */
/**
 * Rsquare Manage Server
 * Api Document
 *
 * The version of the OpenAPI document: V22.20.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { GetAddrOut } from '../model';
/**
 * AddrGovControllerApi - axios parameter creator
 * @export
 */
export const AddrGovControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 키워드 조회
         * @param {string} authorization 
         * @param {number} countPerPage countPerPage
         * @param {number} currentPage currentPage
         * @param {string} keyword keyword
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAddr: async (authorization: string, countPerPage: number, currentPage: number, keyword: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('getAddr', 'authorization', authorization)
            // verify required parameter 'countPerPage' is not null or undefined
            assertParamExists('getAddr', 'countPerPage', countPerPage)
            // verify required parameter 'currentPage' is not null or undefined
            assertParamExists('getAddr', 'currentPage', currentPage)
            // verify required parameter 'keyword' is not null or undefined
            assertParamExists('getAddr', 'keyword', keyword)
            const localVarPath = `/addr-gov`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (countPerPage !== undefined) {
                localVarQueryParameter['countPerPage'] = countPerPage;
            }

            if (currentPage !== undefined) {
                localVarQueryParameter['currentPage'] = currentPage;
            }

            if (keyword !== undefined) {
                localVarQueryParameter['keyword'] = keyword;
            }

            if (authorization !== undefined && authorization !== null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AddrGovControllerApi - functional programming interface
 * @export
 */
export const AddrGovControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AddrGovControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 키워드 조회
         * @param {string} authorization 
         * @param {number} countPerPage countPerPage
         * @param {number} currentPage currentPage
         * @param {string} keyword keyword
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAddr(authorization: string, countPerPage: number, currentPage: number, keyword: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetAddrOut>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAddr(authorization, countPerPage, currentPage, keyword, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * AddrGovControllerApi - factory interface
 * @export
 */
export const AddrGovControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AddrGovControllerApiFp(configuration)
    return {
        /**
         * 
         * @summary 키워드 조회
         * @param {string} authorization 
         * @param {number} countPerPage countPerPage
         * @param {number} currentPage currentPage
         * @param {string} keyword keyword
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAddr(authorization: string, countPerPage: number, currentPage: number, keyword: string, options?: any): AxiosPromise<GetAddrOut> {
            return localVarFp.getAddr(authorization, countPerPage, currentPage, keyword, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AddrGovControllerApi - object-oriented interface
 * @export
 * @class AddrGovControllerApi
 * @extends {BaseAPI}
 */
export class AddrGovControllerApi extends BaseAPI {
    /**
     * 
     * @summary 키워드 조회
     * @param {string} authorization 
     * @param {number} countPerPage countPerPage
     * @param {number} currentPage currentPage
     * @param {string} keyword keyword
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AddrGovControllerApi
     */
    public getAddr(authorization: string, countPerPage: number, currentPage: number, keyword: string, options?: AxiosRequestConfig) {
        return AddrGovControllerApiFp(this.configuration).getAddr(authorization, countPerPage, currentPage, keyword, options).then((request) => request(this.axios, this.basePath));
    }
}
