/* tslint:disable */
/* eslint-disable */
/**
 * Rsquare Manage Server
 * Api Document
 *
 * The version of the OpenAPI document: V22.20.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { GetContrFeeInfo } from '../model';
// @ts-ignore
import { GetContrInfoOut } from '../model';
// @ts-ignore
import { GetContrInfoToFeeOut } from '../model';
// @ts-ignore
import { GetFeeInfoListOut } from '../model';
// @ts-ignore
import { GetFeeInfoOneOut } from '../model';
// @ts-ignore
import { PagingGetFeeListOut } from '../model';
// @ts-ignore
import { PatchFeeInfoIn } from '../model';
// @ts-ignore
import { PatchSavingInfoIn } from '../model';
// @ts-ignore
import { PostFeeInfoIn } from '../model';
// @ts-ignore
import { PostSavingInfoIn } from '../model';
// @ts-ignore
import { Resource } from '../model';
/**
 * FeeControllerApi - axios parameter creator
 * @export
 */
export const FeeControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 수수료 삭제
         * @param {string} authorization 
         * @param {string} contrId contrId
         * @param {string} feeId feeId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteFeeInfo: async (authorization: string, contrId: string, feeId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('deleteFeeInfo', 'authorization', authorization)
            // verify required parameter 'contrId' is not null or undefined
            assertParamExists('deleteFeeInfo', 'contrId', contrId)
            // verify required parameter 'feeId' is not null or undefined
            assertParamExists('deleteFeeInfo', 'feeId', feeId)
            const localVarPath = `/contr/fee/{contrId}/{feeId}`
                .replace(`{${"contrId"}}`, encodeURIComponent(String(contrId)))
                .replace(`{${"feeId"}}`, encodeURIComponent(String(feeId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (authorization !== undefined && authorization !== null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 수수료 입금 정보 삭제
         * @param {string} authorization 
         * @param {string} feeId feeId
         * @param {number} seq seq
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteSavingInfo: async (authorization: string, feeId: string, seq: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('deleteSavingInfo', 'authorization', authorization)
            // verify required parameter 'feeId' is not null or undefined
            assertParamExists('deleteSavingInfo', 'feeId', feeId)
            // verify required parameter 'seq' is not null or undefined
            assertParamExists('deleteSavingInfo', 'seq', seq)
            const localVarPath = `/contr/fee/saving-info/{feeId}/{seq}`
                .replace(`{${"feeId"}}`, encodeURIComponent(String(feeId)))
                .replace(`{${"seq"}}`, encodeURIComponent(String(seq)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (authorization !== undefined && authorization !== null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 계약에 수수료 정보 리스트 조회
         * @param {string} authorization 
         * @param {string} [contrId] contrId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getContrFeeList: async (authorization: string, contrId?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('getContrFeeList', 'authorization', authorization)
            const localVarPath = `/contr/fee/info`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (contrId !== undefined) {
                localVarQueryParameter['contrId'] = contrId;
            }

            if (authorization !== undefined && authorization !== null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 계약정보 리스트 조회
         * @param {string} authorization 
         * @param {string} [contrId] contrId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getContrInfoList: async (authorization: string, contrId?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('getContrInfoList', 'authorization', authorization)
            const localVarPath = `/contr/fee/contr-info`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (contrId !== undefined) {
                localVarQueryParameter['contrId'] = contrId;
            }

            if (authorization !== undefined && authorization !== null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 계약 수수료 입금 상태 조회
         * @param {string} authorization 
         * @param {string} [contrId] contrId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getContrInfoOfSavingStat: async (authorization: string, contrId?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('getContrInfoOfSavingStat', 'authorization', authorization)
            const localVarPath = `/contr/fee/contr-info/saving-stat`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (contrId !== undefined) {
                localVarQueryParameter['contrId'] = contrId;
            }

            if (authorization !== undefined && authorization !== null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 계약 거래처에 따른 수수료 정보 조회
         * @param {string} authorization 
         * @param {string} [clnId] clnId
         * @param {string} [contrId] contrId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getContrInfoOne: async (authorization: string, clnId?: string, contrId?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('getContrInfoOne', 'authorization', authorization)
            const localVarPath = `/contr/fee/contr-cln/fee-info`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (clnId !== undefined) {
                localVarQueryParameter['clnId'] = clnId;
            }

            if (contrId !== undefined) {
                localVarQueryParameter['contrId'] = contrId;
            }

            if (authorization !== undefined && authorization !== null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 수수료 정보 리스트 조회
         * @param {string} authorization 
         * @param {string} [contrId] contrId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFeeInfoList: async (authorization: string, contrId?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('getFeeInfoList', 'authorization', authorization)
            const localVarPath = `/contr/fee/fee-list`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (contrId !== undefined) {
                localVarQueryParameter['contrId'] = contrId;
            }

            if (authorization !== undefined && authorization !== null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 수수료 정보 단건 조회
         * @param {string} authorization 
         * @param {string} [contrId] contrId
         * @param {string} [feeId] feeId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFeeInfoOne: async (authorization: string, contrId?: string, feeId?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('getFeeInfoOne', 'authorization', authorization)
            const localVarPath = `/contr/fee/fee-info`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (contrId !== undefined) {
                localVarQueryParameter['contrId'] = contrId;
            }

            if (feeId !== undefined) {
                localVarQueryParameter['feeId'] = feeId;
            }

            if (authorization !== undefined && authorization !== null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 수수료 목록 조회
         * @param {string} authorization 
         * @param {string} [clnName] 
         * @param {string} [contrId] 
         * @param {string} [feeId] 
         * @param {string} [feePymtAgrmtYn] 
         * @param {string} [maxBalancePmtDy] 
         * @param {string} [maxContrDy] 
         * @param {string} [maxSavingDueDy] 
         * @param {string} [maxSavingDy] 
         * @param {string} [maxTaxinvDueDy] 
         * @param {string} [maxTaxinvIssDy] 
         * @param {number} [maxVatTotalFeeAmt] 
         * @param {string} [minBalancePmtDy] 
         * @param {string} [minContrDy] 
         * @param {string} [minSavingDueDy] 
         * @param {string} [minSavingDy] 
         * @param {string} [minTaxinvDueDy] 
         * @param {string} [minTaxinvIssDy] 
         * @param {number} [minVatTotalFeeAmt] 
         * @param {string} [orderBy] 
         * @param {number} [pageNum] 
         * @param {number} [pageSize] 
         * @param {Array<string>} [savingStatCd] 
         * @param {string} [savingYn] 
         * @param {Array<string>} [taxinvIssStatCd] 
         * @param {string} [taxinvIssYn] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFeePaging: async (authorization: string, clnName?: string, contrId?: string, feeId?: string, feePymtAgrmtYn?: string, maxBalancePmtDy?: string, maxContrDy?: string, maxSavingDueDy?: string, maxSavingDy?: string, maxTaxinvDueDy?: string, maxTaxinvIssDy?: string, maxVatTotalFeeAmt?: number, minBalancePmtDy?: string, minContrDy?: string, minSavingDueDy?: string, minSavingDy?: string, minTaxinvDueDy?: string, minTaxinvIssDy?: string, minVatTotalFeeAmt?: number, orderBy?: string, pageNum?: number, pageSize?: number, savingStatCd?: Array<string>, savingYn?: string, taxinvIssStatCd?: Array<string>, taxinvIssYn?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('getFeePaging', 'authorization', authorization)
            const localVarPath = `/contr/fee`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (clnName !== undefined) {
                localVarQueryParameter['clnName'] = clnName;
            }

            if (contrId !== undefined) {
                localVarQueryParameter['contrId'] = contrId;
            }

            if (feeId !== undefined) {
                localVarQueryParameter['feeId'] = feeId;
            }

            if (feePymtAgrmtYn !== undefined) {
                localVarQueryParameter['feePymtAgrmtYn'] = feePymtAgrmtYn;
            }

            if (maxBalancePmtDy !== undefined) {
                localVarQueryParameter['maxBalancePmtDy'] = maxBalancePmtDy;
            }

            if (maxContrDy !== undefined) {
                localVarQueryParameter['maxContrDy'] = maxContrDy;
            }

            if (maxSavingDueDy !== undefined) {
                localVarQueryParameter['maxSavingDueDy'] = maxSavingDueDy;
            }

            if (maxSavingDy !== undefined) {
                localVarQueryParameter['maxSavingDy'] = maxSavingDy;
            }

            if (maxTaxinvDueDy !== undefined) {
                localVarQueryParameter['maxTaxinvDueDy'] = maxTaxinvDueDy;
            }

            if (maxTaxinvIssDy !== undefined) {
                localVarQueryParameter['maxTaxinvIssDy'] = maxTaxinvIssDy;
            }

            if (maxVatTotalFeeAmt !== undefined) {
                localVarQueryParameter['maxVatTotalFeeAmt'] = maxVatTotalFeeAmt;
            }

            if (minBalancePmtDy !== undefined) {
                localVarQueryParameter['minBalancePmtDy'] = minBalancePmtDy;
            }

            if (minContrDy !== undefined) {
                localVarQueryParameter['minContrDy'] = minContrDy;
            }

            if (minSavingDueDy !== undefined) {
                localVarQueryParameter['minSavingDueDy'] = minSavingDueDy;
            }

            if (minSavingDy !== undefined) {
                localVarQueryParameter['minSavingDy'] = minSavingDy;
            }

            if (minTaxinvDueDy !== undefined) {
                localVarQueryParameter['minTaxinvDueDy'] = minTaxinvDueDy;
            }

            if (minTaxinvIssDy !== undefined) {
                localVarQueryParameter['minTaxinvIssDy'] = minTaxinvIssDy;
            }

            if (minVatTotalFeeAmt !== undefined) {
                localVarQueryParameter['minVatTotalFeeAmt'] = minVatTotalFeeAmt;
            }

            if (orderBy !== undefined) {
                localVarQueryParameter['orderBy'] = orderBy;
            }

            if (pageNum !== undefined) {
                localVarQueryParameter['pageNum'] = pageNum;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }

            if (savingStatCd) {
                localVarQueryParameter['savingStatCd'] = savingStatCd;
            }

            if (savingYn !== undefined) {
                localVarQueryParameter['savingYn'] = savingYn;
            }

            if (taxinvIssStatCd) {
                localVarQueryParameter['taxinvIssStatCd'] = taxinvIssStatCd;
            }

            if (taxinvIssYn !== undefined) {
                localVarQueryParameter['taxinvIssYn'] = taxinvIssYn;
            }

            if (authorization !== undefined && authorization !== null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 수수료 수정
         * @param {string} authorization 
         * @param {string} contrId contrId
         * @param {string} feeId feeId
         * @param {PatchFeeInfoIn} input input
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        patchFeeInfo: async (authorization: string, contrId: string, feeId: string, input: PatchFeeInfoIn, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('patchFeeInfo', 'authorization', authorization)
            // verify required parameter 'contrId' is not null or undefined
            assertParamExists('patchFeeInfo', 'contrId', contrId)
            // verify required parameter 'feeId' is not null or undefined
            assertParamExists('patchFeeInfo', 'feeId', feeId)
            // verify required parameter 'input' is not null or undefined
            assertParamExists('patchFeeInfo', 'input', input)
            const localVarPath = `/contr/fee/{contrId}/{feeId}`
                .replace(`{${"contrId"}}`, encodeURIComponent(String(contrId)))
                .replace(`{${"feeId"}}`, encodeURIComponent(String(feeId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (authorization !== undefined && authorization !== null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(input, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 수수료 입금 상태 수정
         * @param {string} authorization 
         * @param {string} contrId contrId
         * @param {string} savingFeeStatCd savingFeeStatCd
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        patchFeeSavingStat: async (authorization: string, contrId: string, savingFeeStatCd: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('patchFeeSavingStat', 'authorization', authorization)
            // verify required parameter 'contrId' is not null or undefined
            assertParamExists('patchFeeSavingStat', 'contrId', contrId)
            // verify required parameter 'savingFeeStatCd' is not null or undefined
            assertParamExists('patchFeeSavingStat', 'savingFeeStatCd', savingFeeStatCd)
            const localVarPath = `/contr/fee/saving-stat/{contrId}/{savingFeeStatCd}`
                .replace(`{${"contrId"}}`, encodeURIComponent(String(contrId)))
                .replace(`{${"savingFeeStatCd"}}`, encodeURIComponent(String(savingFeeStatCd)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (authorization !== undefined && authorization !== null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 수수료 입금 정보 수정
         * @param {string} authorization 
         * @param {string} feeId feeId
         * @param {number} seq seq
         * @param {PatchSavingInfoIn} input input
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        patchSavingInfo: async (authorization: string, feeId: string, seq: number, input: PatchSavingInfoIn, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('patchSavingInfo', 'authorization', authorization)
            // verify required parameter 'feeId' is not null or undefined
            assertParamExists('patchSavingInfo', 'feeId', feeId)
            // verify required parameter 'seq' is not null or undefined
            assertParamExists('patchSavingInfo', 'seq', seq)
            // verify required parameter 'input' is not null or undefined
            assertParamExists('patchSavingInfo', 'input', input)
            const localVarPath = `/contr/fee/saving-info/{feeId}/{seq}`
                .replace(`{${"feeId"}}`, encodeURIComponent(String(feeId)))
                .replace(`{${"seq"}}`, encodeURIComponent(String(seq)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (authorization !== undefined && authorization !== null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(input, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 수수료 등록
         * @param {string} authorization 
         * @param {string} contrId contrId
         * @param {PostFeeInfoIn} input input
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postFeeInfo: async (authorization: string, contrId: string, input: PostFeeInfoIn, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('postFeeInfo', 'authorization', authorization)
            // verify required parameter 'contrId' is not null or undefined
            assertParamExists('postFeeInfo', 'contrId', contrId)
            // verify required parameter 'input' is not null or undefined
            assertParamExists('postFeeInfo', 'input', input)
            const localVarPath = `/contr/fee/{contrId}`
                .replace(`{${"contrId"}}`, encodeURIComponent(String(contrId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (authorization !== undefined && authorization !== null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(input, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 수수료 입금 정보 등록
         * @param {string} authorization 
         * @param {string} feeId feeId
         * @param {PostSavingInfoIn} input input
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postSavingInfo: async (authorization: string, feeId: string, input: PostSavingInfoIn, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('postSavingInfo', 'authorization', authorization)
            // verify required parameter 'feeId' is not null or undefined
            assertParamExists('postSavingInfo', 'feeId', feeId)
            // verify required parameter 'input' is not null or undefined
            assertParamExists('postSavingInfo', 'input', input)
            const localVarPath = `/contr/fee/saving-info/{feeId}`
                .replace(`{${"feeId"}}`, encodeURIComponent(String(feeId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (authorization !== undefined && authorization !== null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(input, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 수수료 엑셀 다운로드
         * @param {string} authorization 
         * @param {string} [clnName] 
         * @param {string} [contrId] 
         * @param {string} [feeId] 
         * @param {string} [feePymtAgrmtYn] 
         * @param {string} [maxBalancePmtDy] 
         * @param {string} [maxContrDy] 
         * @param {string} [maxSavingDueDy] 
         * @param {string} [maxSavingDy] 
         * @param {string} [maxTaxinvDueDy] 
         * @param {string} [maxTaxinvIssDy] 
         * @param {number} [maxVatTotalFeeAmt] 
         * @param {string} [minBalancePmtDy] 
         * @param {string} [minContrDy] 
         * @param {string} [minSavingDueDy] 
         * @param {string} [minSavingDy] 
         * @param {string} [minTaxinvDueDy] 
         * @param {string} [minTaxinvIssDy] 
         * @param {number} [minVatTotalFeeAmt] 
         * @param {string} [orderBy] 
         * @param {number} [pageNum] 
         * @param {number} [pageSize] 
         * @param {Array<string>} [savingStatCd] 
         * @param {string} [savingYn] 
         * @param {Array<string>} [taxinvIssStatCd] 
         * @param {string} [taxinvIssYn] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        selectFeeListDownloadExcel: async (authorization: string, clnName?: string, contrId?: string, feeId?: string, feePymtAgrmtYn?: string, maxBalancePmtDy?: string, maxContrDy?: string, maxSavingDueDy?: string, maxSavingDy?: string, maxTaxinvDueDy?: string, maxTaxinvIssDy?: string, maxVatTotalFeeAmt?: number, minBalancePmtDy?: string, minContrDy?: string, minSavingDueDy?: string, minSavingDy?: string, minTaxinvDueDy?: string, minTaxinvIssDy?: string, minVatTotalFeeAmt?: number, orderBy?: string, pageNum?: number, pageSize?: number, savingStatCd?: Array<string>, savingYn?: string, taxinvIssStatCd?: Array<string>, taxinvIssYn?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('selectFeeListDownloadExcel', 'authorization', authorization)
            const localVarPath = `/contr/fee/excel-download`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (clnName !== undefined) {
                localVarQueryParameter['clnName'] = clnName;
            }

            if (contrId !== undefined) {
                localVarQueryParameter['contrId'] = contrId;
            }

            if (feeId !== undefined) {
                localVarQueryParameter['feeId'] = feeId;
            }

            if (feePymtAgrmtYn !== undefined) {
                localVarQueryParameter['feePymtAgrmtYn'] = feePymtAgrmtYn;
            }

            if (maxBalancePmtDy !== undefined) {
                localVarQueryParameter['maxBalancePmtDy'] = maxBalancePmtDy;
            }

            if (maxContrDy !== undefined) {
                localVarQueryParameter['maxContrDy'] = maxContrDy;
            }

            if (maxSavingDueDy !== undefined) {
                localVarQueryParameter['maxSavingDueDy'] = maxSavingDueDy;
            }

            if (maxSavingDy !== undefined) {
                localVarQueryParameter['maxSavingDy'] = maxSavingDy;
            }

            if (maxTaxinvDueDy !== undefined) {
                localVarQueryParameter['maxTaxinvDueDy'] = maxTaxinvDueDy;
            }

            if (maxTaxinvIssDy !== undefined) {
                localVarQueryParameter['maxTaxinvIssDy'] = maxTaxinvIssDy;
            }

            if (maxVatTotalFeeAmt !== undefined) {
                localVarQueryParameter['maxVatTotalFeeAmt'] = maxVatTotalFeeAmt;
            }

            if (minBalancePmtDy !== undefined) {
                localVarQueryParameter['minBalancePmtDy'] = minBalancePmtDy;
            }

            if (minContrDy !== undefined) {
                localVarQueryParameter['minContrDy'] = minContrDy;
            }

            if (minSavingDueDy !== undefined) {
                localVarQueryParameter['minSavingDueDy'] = minSavingDueDy;
            }

            if (minSavingDy !== undefined) {
                localVarQueryParameter['minSavingDy'] = minSavingDy;
            }

            if (minTaxinvDueDy !== undefined) {
                localVarQueryParameter['minTaxinvDueDy'] = minTaxinvDueDy;
            }

            if (minTaxinvIssDy !== undefined) {
                localVarQueryParameter['minTaxinvIssDy'] = minTaxinvIssDy;
            }

            if (minVatTotalFeeAmt !== undefined) {
                localVarQueryParameter['minVatTotalFeeAmt'] = minVatTotalFeeAmt;
            }

            if (orderBy !== undefined) {
                localVarQueryParameter['orderBy'] = orderBy;
            }

            if (pageNum !== undefined) {
                localVarQueryParameter['pageNum'] = pageNum;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }

            if (savingStatCd) {
                localVarQueryParameter['savingStatCd'] = savingStatCd;
            }

            if (savingYn !== undefined) {
                localVarQueryParameter['savingYn'] = savingYn;
            }

            if (taxinvIssStatCd) {
                localVarQueryParameter['taxinvIssStatCd'] = taxinvIssStatCd;
            }

            if (taxinvIssYn !== undefined) {
                localVarQueryParameter['taxinvIssYn'] = taxinvIssYn;
            }

            if (authorization !== undefined && authorization !== null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * FeeControllerApi - functional programming interface
 * @export
 */
export const FeeControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = FeeControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 수수료 삭제
         * @param {string} authorization 
         * @param {string} contrId contrId
         * @param {string} feeId feeId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteFeeInfo(authorization: string, contrId: string, feeId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<number>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteFeeInfo(authorization, contrId, feeId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary 수수료 입금 정보 삭제
         * @param {string} authorization 
         * @param {string} feeId feeId
         * @param {number} seq seq
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteSavingInfo(authorization: string, feeId: string, seq: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<number>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteSavingInfo(authorization, feeId, seq, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary 계약에 수수료 정보 리스트 조회
         * @param {string} authorization 
         * @param {string} [contrId] contrId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getContrFeeList(authorization: string, contrId?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<GetContrFeeInfo>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getContrFeeList(authorization, contrId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary 계약정보 리스트 조회
         * @param {string} authorization 
         * @param {string} [contrId] contrId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getContrInfoList(authorization: string, contrId?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<GetContrInfoOut>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getContrInfoList(authorization, contrId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary 계약 수수료 입금 상태 조회
         * @param {string} authorization 
         * @param {string} [contrId] contrId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getContrInfoOfSavingStat(authorization: string, contrId?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetContrInfoToFeeOut>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getContrInfoOfSavingStat(authorization, contrId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary 계약 거래처에 따른 수수료 정보 조회
         * @param {string} authorization 
         * @param {string} [clnId] clnId
         * @param {string} [contrId] contrId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getContrInfoOne(authorization: string, clnId?: string, contrId?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetContrInfoOut>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getContrInfoOne(authorization, clnId, contrId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary 수수료 정보 리스트 조회
         * @param {string} authorization 
         * @param {string} [contrId] contrId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getFeeInfoList(authorization: string, contrId?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<GetFeeInfoListOut>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getFeeInfoList(authorization, contrId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary 수수료 정보 단건 조회
         * @param {string} authorization 
         * @param {string} [contrId] contrId
         * @param {string} [feeId] feeId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getFeeInfoOne(authorization: string, contrId?: string, feeId?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetFeeInfoOneOut>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getFeeInfoOne(authorization, contrId, feeId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary 수수료 목록 조회
         * @param {string} authorization 
         * @param {string} [clnName] 
         * @param {string} [contrId] 
         * @param {string} [feeId] 
         * @param {string} [feePymtAgrmtYn] 
         * @param {string} [maxBalancePmtDy] 
         * @param {string} [maxContrDy] 
         * @param {string} [maxSavingDueDy] 
         * @param {string} [maxSavingDy] 
         * @param {string} [maxTaxinvDueDy] 
         * @param {string} [maxTaxinvIssDy] 
         * @param {number} [maxVatTotalFeeAmt] 
         * @param {string} [minBalancePmtDy] 
         * @param {string} [minContrDy] 
         * @param {string} [minSavingDueDy] 
         * @param {string} [minSavingDy] 
         * @param {string} [minTaxinvDueDy] 
         * @param {string} [minTaxinvIssDy] 
         * @param {number} [minVatTotalFeeAmt] 
         * @param {string} [orderBy] 
         * @param {number} [pageNum] 
         * @param {number} [pageSize] 
         * @param {Array<string>} [savingStatCd] 
         * @param {string} [savingYn] 
         * @param {Array<string>} [taxinvIssStatCd] 
         * @param {string} [taxinvIssYn] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getFeePaging(authorization: string, clnName?: string, contrId?: string, feeId?: string, feePymtAgrmtYn?: string, maxBalancePmtDy?: string, maxContrDy?: string, maxSavingDueDy?: string, maxSavingDy?: string, maxTaxinvDueDy?: string, maxTaxinvIssDy?: string, maxVatTotalFeeAmt?: number, minBalancePmtDy?: string, minContrDy?: string, minSavingDueDy?: string, minSavingDy?: string, minTaxinvDueDy?: string, minTaxinvIssDy?: string, minVatTotalFeeAmt?: number, orderBy?: string, pageNum?: number, pageSize?: number, savingStatCd?: Array<string>, savingYn?: string, taxinvIssStatCd?: Array<string>, taxinvIssYn?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PagingGetFeeListOut>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getFeePaging(authorization, clnName, contrId, feeId, feePymtAgrmtYn, maxBalancePmtDy, maxContrDy, maxSavingDueDy, maxSavingDy, maxTaxinvDueDy, maxTaxinvIssDy, maxVatTotalFeeAmt, minBalancePmtDy, minContrDy, minSavingDueDy, minSavingDy, minTaxinvDueDy, minTaxinvIssDy, minVatTotalFeeAmt, orderBy, pageNum, pageSize, savingStatCd, savingYn, taxinvIssStatCd, taxinvIssYn, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary 수수료 수정
         * @param {string} authorization 
         * @param {string} contrId contrId
         * @param {string} feeId feeId
         * @param {PatchFeeInfoIn} input input
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async patchFeeInfo(authorization: string, contrId: string, feeId: string, input: PatchFeeInfoIn, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<number>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.patchFeeInfo(authorization, contrId, feeId, input, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary 수수료 입금 상태 수정
         * @param {string} authorization 
         * @param {string} contrId contrId
         * @param {string} savingFeeStatCd savingFeeStatCd
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async patchFeeSavingStat(authorization: string, contrId: string, savingFeeStatCd: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<number>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.patchFeeSavingStat(authorization, contrId, savingFeeStatCd, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary 수수료 입금 정보 수정
         * @param {string} authorization 
         * @param {string} feeId feeId
         * @param {number} seq seq
         * @param {PatchSavingInfoIn} input input
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async patchSavingInfo(authorization: string, feeId: string, seq: number, input: PatchSavingInfoIn, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<number>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.patchSavingInfo(authorization, feeId, seq, input, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary 수수료 등록
         * @param {string} authorization 
         * @param {string} contrId contrId
         * @param {PostFeeInfoIn} input input
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postFeeInfo(authorization: string, contrId: string, input: PostFeeInfoIn, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<number>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postFeeInfo(authorization, contrId, input, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary 수수료 입금 정보 등록
         * @param {string} authorization 
         * @param {string} feeId feeId
         * @param {PostSavingInfoIn} input input
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postSavingInfo(authorization: string, feeId: string, input: PostSavingInfoIn, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<number>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postSavingInfo(authorization, feeId, input, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary 수수료 엑셀 다운로드
         * @param {string} authorization 
         * @param {string} [clnName] 
         * @param {string} [contrId] 
         * @param {string} [feeId] 
         * @param {string} [feePymtAgrmtYn] 
         * @param {string} [maxBalancePmtDy] 
         * @param {string} [maxContrDy] 
         * @param {string} [maxSavingDueDy] 
         * @param {string} [maxSavingDy] 
         * @param {string} [maxTaxinvDueDy] 
         * @param {string} [maxTaxinvIssDy] 
         * @param {number} [maxVatTotalFeeAmt] 
         * @param {string} [minBalancePmtDy] 
         * @param {string} [minContrDy] 
         * @param {string} [minSavingDueDy] 
         * @param {string} [minSavingDy] 
         * @param {string} [minTaxinvDueDy] 
         * @param {string} [minTaxinvIssDy] 
         * @param {number} [minVatTotalFeeAmt] 
         * @param {string} [orderBy] 
         * @param {number} [pageNum] 
         * @param {number} [pageSize] 
         * @param {Array<string>} [savingStatCd] 
         * @param {string} [savingYn] 
         * @param {Array<string>} [taxinvIssStatCd] 
         * @param {string} [taxinvIssYn] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async selectFeeListDownloadExcel(authorization: string, clnName?: string, contrId?: string, feeId?: string, feePymtAgrmtYn?: string, maxBalancePmtDy?: string, maxContrDy?: string, maxSavingDueDy?: string, maxSavingDy?: string, maxTaxinvDueDy?: string, maxTaxinvIssDy?: string, maxVatTotalFeeAmt?: number, minBalancePmtDy?: string, minContrDy?: string, minSavingDueDy?: string, minSavingDy?: string, minTaxinvDueDy?: string, minTaxinvIssDy?: string, minVatTotalFeeAmt?: number, orderBy?: string, pageNum?: number, pageSize?: number, savingStatCd?: Array<string>, savingYn?: string, taxinvIssStatCd?: Array<string>, taxinvIssYn?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Resource>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.selectFeeListDownloadExcel(authorization, clnName, contrId, feeId, feePymtAgrmtYn, maxBalancePmtDy, maxContrDy, maxSavingDueDy, maxSavingDy, maxTaxinvDueDy, maxTaxinvIssDy, maxVatTotalFeeAmt, minBalancePmtDy, minContrDy, minSavingDueDy, minSavingDy, minTaxinvDueDy, minTaxinvIssDy, minVatTotalFeeAmt, orderBy, pageNum, pageSize, savingStatCd, savingYn, taxinvIssStatCd, taxinvIssYn, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * FeeControllerApi - factory interface
 * @export
 */
export const FeeControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = FeeControllerApiFp(configuration)
    return {
        /**
         * 
         * @summary 수수료 삭제
         * @param {string} authorization 
         * @param {string} contrId contrId
         * @param {string} feeId feeId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteFeeInfo(authorization: string, contrId: string, feeId: string, options?: any): AxiosPromise<number> {
            return localVarFp.deleteFeeInfo(authorization, contrId, feeId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 수수료 입금 정보 삭제
         * @param {string} authorization 
         * @param {string} feeId feeId
         * @param {number} seq seq
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteSavingInfo(authorization: string, feeId: string, seq: number, options?: any): AxiosPromise<number> {
            return localVarFp.deleteSavingInfo(authorization, feeId, seq, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 계약에 수수료 정보 리스트 조회
         * @param {string} authorization 
         * @param {string} [contrId] contrId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getContrFeeList(authorization: string, contrId?: string, options?: any): AxiosPromise<Array<GetContrFeeInfo>> {
            return localVarFp.getContrFeeList(authorization, contrId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 계약정보 리스트 조회
         * @param {string} authorization 
         * @param {string} [contrId] contrId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getContrInfoList(authorization: string, contrId?: string, options?: any): AxiosPromise<Array<GetContrInfoOut>> {
            return localVarFp.getContrInfoList(authorization, contrId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 계약 수수료 입금 상태 조회
         * @param {string} authorization 
         * @param {string} [contrId] contrId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getContrInfoOfSavingStat(authorization: string, contrId?: string, options?: any): AxiosPromise<GetContrInfoToFeeOut> {
            return localVarFp.getContrInfoOfSavingStat(authorization, contrId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 계약 거래처에 따른 수수료 정보 조회
         * @param {string} authorization 
         * @param {string} [clnId] clnId
         * @param {string} [contrId] contrId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getContrInfoOne(authorization: string, clnId?: string, contrId?: string, options?: any): AxiosPromise<GetContrInfoOut> {
            return localVarFp.getContrInfoOne(authorization, clnId, contrId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 수수료 정보 리스트 조회
         * @param {string} authorization 
         * @param {string} [contrId] contrId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFeeInfoList(authorization: string, contrId?: string, options?: any): AxiosPromise<Array<GetFeeInfoListOut>> {
            return localVarFp.getFeeInfoList(authorization, contrId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 수수료 정보 단건 조회
         * @param {string} authorization 
         * @param {string} [contrId] contrId
         * @param {string} [feeId] feeId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFeeInfoOne(authorization: string, contrId?: string, feeId?: string, options?: any): AxiosPromise<GetFeeInfoOneOut> {
            return localVarFp.getFeeInfoOne(authorization, contrId, feeId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 수수료 목록 조회
         * @param {string} authorization 
         * @param {string} [clnName] 
         * @param {string} [contrId] 
         * @param {string} [feeId] 
         * @param {string} [feePymtAgrmtYn] 
         * @param {string} [maxBalancePmtDy] 
         * @param {string} [maxContrDy] 
         * @param {string} [maxSavingDueDy] 
         * @param {string} [maxSavingDy] 
         * @param {string} [maxTaxinvDueDy] 
         * @param {string} [maxTaxinvIssDy] 
         * @param {number} [maxVatTotalFeeAmt] 
         * @param {string} [minBalancePmtDy] 
         * @param {string} [minContrDy] 
         * @param {string} [minSavingDueDy] 
         * @param {string} [minSavingDy] 
         * @param {string} [minTaxinvDueDy] 
         * @param {string} [minTaxinvIssDy] 
         * @param {number} [minVatTotalFeeAmt] 
         * @param {string} [orderBy] 
         * @param {number} [pageNum] 
         * @param {number} [pageSize] 
         * @param {Array<string>} [savingStatCd] 
         * @param {string} [savingYn] 
         * @param {Array<string>} [taxinvIssStatCd] 
         * @param {string} [taxinvIssYn] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFeePaging(authorization: string, clnName?: string, contrId?: string, feeId?: string, feePymtAgrmtYn?: string, maxBalancePmtDy?: string, maxContrDy?: string, maxSavingDueDy?: string, maxSavingDy?: string, maxTaxinvDueDy?: string, maxTaxinvIssDy?: string, maxVatTotalFeeAmt?: number, minBalancePmtDy?: string, minContrDy?: string, minSavingDueDy?: string, minSavingDy?: string, minTaxinvDueDy?: string, minTaxinvIssDy?: string, minVatTotalFeeAmt?: number, orderBy?: string, pageNum?: number, pageSize?: number, savingStatCd?: Array<string>, savingYn?: string, taxinvIssStatCd?: Array<string>, taxinvIssYn?: string, options?: any): AxiosPromise<PagingGetFeeListOut> {
            return localVarFp.getFeePaging(authorization, clnName, contrId, feeId, feePymtAgrmtYn, maxBalancePmtDy, maxContrDy, maxSavingDueDy, maxSavingDy, maxTaxinvDueDy, maxTaxinvIssDy, maxVatTotalFeeAmt, minBalancePmtDy, minContrDy, minSavingDueDy, minSavingDy, minTaxinvDueDy, minTaxinvIssDy, minVatTotalFeeAmt, orderBy, pageNum, pageSize, savingStatCd, savingYn, taxinvIssStatCd, taxinvIssYn, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 수수료 수정
         * @param {string} authorization 
         * @param {string} contrId contrId
         * @param {string} feeId feeId
         * @param {PatchFeeInfoIn} input input
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        patchFeeInfo(authorization: string, contrId: string, feeId: string, input: PatchFeeInfoIn, options?: any): AxiosPromise<number> {
            return localVarFp.patchFeeInfo(authorization, contrId, feeId, input, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 수수료 입금 상태 수정
         * @param {string} authorization 
         * @param {string} contrId contrId
         * @param {string} savingFeeStatCd savingFeeStatCd
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        patchFeeSavingStat(authorization: string, contrId: string, savingFeeStatCd: string, options?: any): AxiosPromise<number> {
            return localVarFp.patchFeeSavingStat(authorization, contrId, savingFeeStatCd, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 수수료 입금 정보 수정
         * @param {string} authorization 
         * @param {string} feeId feeId
         * @param {number} seq seq
         * @param {PatchSavingInfoIn} input input
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        patchSavingInfo(authorization: string, feeId: string, seq: number, input: PatchSavingInfoIn, options?: any): AxiosPromise<number> {
            return localVarFp.patchSavingInfo(authorization, feeId, seq, input, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 수수료 등록
         * @param {string} authorization 
         * @param {string} contrId contrId
         * @param {PostFeeInfoIn} input input
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postFeeInfo(authorization: string, contrId: string, input: PostFeeInfoIn, options?: any): AxiosPromise<number> {
            return localVarFp.postFeeInfo(authorization, contrId, input, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 수수료 입금 정보 등록
         * @param {string} authorization 
         * @param {string} feeId feeId
         * @param {PostSavingInfoIn} input input
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postSavingInfo(authorization: string, feeId: string, input: PostSavingInfoIn, options?: any): AxiosPromise<number> {
            return localVarFp.postSavingInfo(authorization, feeId, input, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 수수료 엑셀 다운로드
         * @param {string} authorization 
         * @param {string} [clnName] 
         * @param {string} [contrId] 
         * @param {string} [feeId] 
         * @param {string} [feePymtAgrmtYn] 
         * @param {string} [maxBalancePmtDy] 
         * @param {string} [maxContrDy] 
         * @param {string} [maxSavingDueDy] 
         * @param {string} [maxSavingDy] 
         * @param {string} [maxTaxinvDueDy] 
         * @param {string} [maxTaxinvIssDy] 
         * @param {number} [maxVatTotalFeeAmt] 
         * @param {string} [minBalancePmtDy] 
         * @param {string} [minContrDy] 
         * @param {string} [minSavingDueDy] 
         * @param {string} [minSavingDy] 
         * @param {string} [minTaxinvDueDy] 
         * @param {string} [minTaxinvIssDy] 
         * @param {number} [minVatTotalFeeAmt] 
         * @param {string} [orderBy] 
         * @param {number} [pageNum] 
         * @param {number} [pageSize] 
         * @param {Array<string>} [savingStatCd] 
         * @param {string} [savingYn] 
         * @param {Array<string>} [taxinvIssStatCd] 
         * @param {string} [taxinvIssYn] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        selectFeeListDownloadExcel(authorization: string, clnName?: string, contrId?: string, feeId?: string, feePymtAgrmtYn?: string, maxBalancePmtDy?: string, maxContrDy?: string, maxSavingDueDy?: string, maxSavingDy?: string, maxTaxinvDueDy?: string, maxTaxinvIssDy?: string, maxVatTotalFeeAmt?: number, minBalancePmtDy?: string, minContrDy?: string, minSavingDueDy?: string, minSavingDy?: string, minTaxinvDueDy?: string, minTaxinvIssDy?: string, minVatTotalFeeAmt?: number, orderBy?: string, pageNum?: number, pageSize?: number, savingStatCd?: Array<string>, savingYn?: string, taxinvIssStatCd?: Array<string>, taxinvIssYn?: string, options?: any): AxiosPromise<Resource> {
            return localVarFp.selectFeeListDownloadExcel(authorization, clnName, contrId, feeId, feePymtAgrmtYn, maxBalancePmtDy, maxContrDy, maxSavingDueDy, maxSavingDy, maxTaxinvDueDy, maxTaxinvIssDy, maxVatTotalFeeAmt, minBalancePmtDy, minContrDy, minSavingDueDy, minSavingDy, minTaxinvDueDy, minTaxinvIssDy, minVatTotalFeeAmt, orderBy, pageNum, pageSize, savingStatCd, savingYn, taxinvIssStatCd, taxinvIssYn, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * FeeControllerApi - object-oriented interface
 * @export
 * @class FeeControllerApi
 * @extends {BaseAPI}
 */
export class FeeControllerApi extends BaseAPI {
    /**
     * 
     * @summary 수수료 삭제
     * @param {string} authorization 
     * @param {string} contrId contrId
     * @param {string} feeId feeId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FeeControllerApi
     */
    public deleteFeeInfo(authorization: string, contrId: string, feeId: string, options?: AxiosRequestConfig) {
        return FeeControllerApiFp(this.configuration).deleteFeeInfo(authorization, contrId, feeId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 수수료 입금 정보 삭제
     * @param {string} authorization 
     * @param {string} feeId feeId
     * @param {number} seq seq
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FeeControllerApi
     */
    public deleteSavingInfo(authorization: string, feeId: string, seq: number, options?: AxiosRequestConfig) {
        return FeeControllerApiFp(this.configuration).deleteSavingInfo(authorization, feeId, seq, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 계약에 수수료 정보 리스트 조회
     * @param {string} authorization 
     * @param {string} [contrId] contrId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FeeControllerApi
     */
    public getContrFeeList(authorization: string, contrId?: string, options?: AxiosRequestConfig) {
        return FeeControllerApiFp(this.configuration).getContrFeeList(authorization, contrId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 계약정보 리스트 조회
     * @param {string} authorization 
     * @param {string} [contrId] contrId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FeeControllerApi
     */
    public getContrInfoList(authorization: string, contrId?: string, options?: AxiosRequestConfig) {
        return FeeControllerApiFp(this.configuration).getContrInfoList(authorization, contrId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 계약 수수료 입금 상태 조회
     * @param {string} authorization 
     * @param {string} [contrId] contrId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FeeControllerApi
     */
    public getContrInfoOfSavingStat(authorization: string, contrId?: string, options?: AxiosRequestConfig) {
        return FeeControllerApiFp(this.configuration).getContrInfoOfSavingStat(authorization, contrId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 계약 거래처에 따른 수수료 정보 조회
     * @param {string} authorization 
     * @param {string} [clnId] clnId
     * @param {string} [contrId] contrId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FeeControllerApi
     */
    public getContrInfoOne(authorization: string, clnId?: string, contrId?: string, options?: AxiosRequestConfig) {
        return FeeControllerApiFp(this.configuration).getContrInfoOne(authorization, clnId, contrId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 수수료 정보 리스트 조회
     * @param {string} authorization 
     * @param {string} [contrId] contrId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FeeControllerApi
     */
    public getFeeInfoList(authorization: string, contrId?: string, options?: AxiosRequestConfig) {
        return FeeControllerApiFp(this.configuration).getFeeInfoList(authorization, contrId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 수수료 정보 단건 조회
     * @param {string} authorization 
     * @param {string} [contrId] contrId
     * @param {string} [feeId] feeId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FeeControllerApi
     */
    public getFeeInfoOne(authorization: string, contrId?: string, feeId?: string, options?: AxiosRequestConfig) {
        return FeeControllerApiFp(this.configuration).getFeeInfoOne(authorization, contrId, feeId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 수수료 목록 조회
     * @param {string} authorization 
     * @param {string} [clnName] 
     * @param {string} [contrId] 
     * @param {string} [feeId] 
     * @param {string} [feePymtAgrmtYn] 
     * @param {string} [maxBalancePmtDy] 
     * @param {string} [maxContrDy] 
     * @param {string} [maxSavingDueDy] 
     * @param {string} [maxSavingDy] 
     * @param {string} [maxTaxinvDueDy] 
     * @param {string} [maxTaxinvIssDy] 
     * @param {number} [maxVatTotalFeeAmt] 
     * @param {string} [minBalancePmtDy] 
     * @param {string} [minContrDy] 
     * @param {string} [minSavingDueDy] 
     * @param {string} [minSavingDy] 
     * @param {string} [minTaxinvDueDy] 
     * @param {string} [minTaxinvIssDy] 
     * @param {number} [minVatTotalFeeAmt] 
     * @param {string} [orderBy] 
     * @param {number} [pageNum] 
     * @param {number} [pageSize] 
     * @param {Array<string>} [savingStatCd] 
     * @param {string} [savingYn] 
     * @param {Array<string>} [taxinvIssStatCd] 
     * @param {string} [taxinvIssYn] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FeeControllerApi
     */
    public getFeePaging(authorization: string, clnName?: string, contrId?: string, feeId?: string, feePymtAgrmtYn?: string, maxBalancePmtDy?: string, maxContrDy?: string, maxSavingDueDy?: string, maxSavingDy?: string, maxTaxinvDueDy?: string, maxTaxinvIssDy?: string, maxVatTotalFeeAmt?: number, minBalancePmtDy?: string, minContrDy?: string, minSavingDueDy?: string, minSavingDy?: string, minTaxinvDueDy?: string, minTaxinvIssDy?: string, minVatTotalFeeAmt?: number, orderBy?: string, pageNum?: number, pageSize?: number, savingStatCd?: Array<string>, savingYn?: string, taxinvIssStatCd?: Array<string>, taxinvIssYn?: string, options?: AxiosRequestConfig) {
        return FeeControllerApiFp(this.configuration).getFeePaging(authorization, clnName, contrId, feeId, feePymtAgrmtYn, maxBalancePmtDy, maxContrDy, maxSavingDueDy, maxSavingDy, maxTaxinvDueDy, maxTaxinvIssDy, maxVatTotalFeeAmt, minBalancePmtDy, minContrDy, minSavingDueDy, minSavingDy, minTaxinvDueDy, minTaxinvIssDy, minVatTotalFeeAmt, orderBy, pageNum, pageSize, savingStatCd, savingYn, taxinvIssStatCd, taxinvIssYn, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 수수료 수정
     * @param {string} authorization 
     * @param {string} contrId contrId
     * @param {string} feeId feeId
     * @param {PatchFeeInfoIn} input input
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FeeControllerApi
     */
    public patchFeeInfo(authorization: string, contrId: string, feeId: string, input: PatchFeeInfoIn, options?: AxiosRequestConfig) {
        return FeeControllerApiFp(this.configuration).patchFeeInfo(authorization, contrId, feeId, input, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 수수료 입금 상태 수정
     * @param {string} authorization 
     * @param {string} contrId contrId
     * @param {string} savingFeeStatCd savingFeeStatCd
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FeeControllerApi
     */
    public patchFeeSavingStat(authorization: string, contrId: string, savingFeeStatCd: string, options?: AxiosRequestConfig) {
        return FeeControllerApiFp(this.configuration).patchFeeSavingStat(authorization, contrId, savingFeeStatCd, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 수수료 입금 정보 수정
     * @param {string} authorization 
     * @param {string} feeId feeId
     * @param {number} seq seq
     * @param {PatchSavingInfoIn} input input
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FeeControllerApi
     */
    public patchSavingInfo(authorization: string, feeId: string, seq: number, input: PatchSavingInfoIn, options?: AxiosRequestConfig) {
        return FeeControllerApiFp(this.configuration).patchSavingInfo(authorization, feeId, seq, input, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 수수료 등록
     * @param {string} authorization 
     * @param {string} contrId contrId
     * @param {PostFeeInfoIn} input input
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FeeControllerApi
     */
    public postFeeInfo(authorization: string, contrId: string, input: PostFeeInfoIn, options?: AxiosRequestConfig) {
        return FeeControllerApiFp(this.configuration).postFeeInfo(authorization, contrId, input, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 수수료 입금 정보 등록
     * @param {string} authorization 
     * @param {string} feeId feeId
     * @param {PostSavingInfoIn} input input
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FeeControllerApi
     */
    public postSavingInfo(authorization: string, feeId: string, input: PostSavingInfoIn, options?: AxiosRequestConfig) {
        return FeeControllerApiFp(this.configuration).postSavingInfo(authorization, feeId, input, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 수수료 엑셀 다운로드
     * @param {string} authorization 
     * @param {string} [clnName] 
     * @param {string} [contrId] 
     * @param {string} [feeId] 
     * @param {string} [feePymtAgrmtYn] 
     * @param {string} [maxBalancePmtDy] 
     * @param {string} [maxContrDy] 
     * @param {string} [maxSavingDueDy] 
     * @param {string} [maxSavingDy] 
     * @param {string} [maxTaxinvDueDy] 
     * @param {string} [maxTaxinvIssDy] 
     * @param {number} [maxVatTotalFeeAmt] 
     * @param {string} [minBalancePmtDy] 
     * @param {string} [minContrDy] 
     * @param {string} [minSavingDueDy] 
     * @param {string} [minSavingDy] 
     * @param {string} [minTaxinvDueDy] 
     * @param {string} [minTaxinvIssDy] 
     * @param {number} [minVatTotalFeeAmt] 
     * @param {string} [orderBy] 
     * @param {number} [pageNum] 
     * @param {number} [pageSize] 
     * @param {Array<string>} [savingStatCd] 
     * @param {string} [savingYn] 
     * @param {Array<string>} [taxinvIssStatCd] 
     * @param {string} [taxinvIssYn] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FeeControllerApi
     */
    public selectFeeListDownloadExcel(authorization: string, clnName?: string, contrId?: string, feeId?: string, feePymtAgrmtYn?: string, maxBalancePmtDy?: string, maxContrDy?: string, maxSavingDueDy?: string, maxSavingDy?: string, maxTaxinvDueDy?: string, maxTaxinvIssDy?: string, maxVatTotalFeeAmt?: number, minBalancePmtDy?: string, minContrDy?: string, minSavingDueDy?: string, minSavingDy?: string, minTaxinvDueDy?: string, minTaxinvIssDy?: string, minVatTotalFeeAmt?: number, orderBy?: string, pageNum?: number, pageSize?: number, savingStatCd?: Array<string>, savingYn?: string, taxinvIssStatCd?: Array<string>, taxinvIssYn?: string, options?: AxiosRequestConfig) {
        return FeeControllerApiFp(this.configuration).selectFeeListDownloadExcel(authorization, clnName, contrId, feeId, feePymtAgrmtYn, maxBalancePmtDy, maxContrDy, maxSavingDueDy, maxSavingDy, maxTaxinvDueDy, maxTaxinvIssDy, maxVatTotalFeeAmt, minBalancePmtDy, minContrDy, minSavingDueDy, minSavingDy, minTaxinvDueDy, minTaxinvIssDy, minVatTotalFeeAmt, orderBy, pageNum, pageSize, savingStatCd, savingYn, taxinvIssStatCd, taxinvIssYn, options).then((request) => request(this.axios, this.basePath));
    }
}
