
/**
*
* Generated by Rsquare Codegen (v3.0.1) (2022-07-22 14:26:31 191)
*
*/

export default interface WwwGetKeywordResult {

  code?: string
  lineName?: string[]
  placeName?: string
  type?: string

}
