
/**
*
* Generated by Rsquare Codegen (v3.0.1) (2022-07-22 14:26:31 191)
*
*/

export default interface WwwGetAllBldPhtOut {

  bldId?: string
  costrStatCd?: string
  exteriorCaptPsblYn?: string
  flrNum?: number
  phtLclCd?: string
  phtLclName?: string
  phtPath?: string
  prdId?: string
  unitCfCd?: string
  unitCfCdName?: string
  unitName?: string

}
