
/**
*
* Generated by Rsquare Codegen (v3.0.1) (2022-07-22 14:26:31 188)
*
*/

export default interface WwwGetPrdPhtOut {

  bldId?: string
  flrNum?: string
  phtLclCd?: string
  phtLclName?: string
  phtPath?: string
  prdId?: string

}
