
/**
*
* Generated by Rsquare Codegen (v3.0.1) (2022-07-22 14:26:31 189)
*
*/

export default interface WwwGetBldBaseInfoOut {

  addr?: string
  allDayOpenTypeCd?: string
  allDayOpenTypeName?: string
  bldDrcnCd?: string
  bldId?: string
  bsmtCnt?: number
  dgName?: string
  dpstAmt?: number
  elvStatCd?: string
  elvStatName?: string
  exclRate?: number
  flrCnt?: number
  flrInfo?: string
  flrNum?: number
  freeParkCnt?: string
  freeParkDtl?: string
  glaM2?: number
  glaPy?: number
  hdyOpenTypeCd?: string
  hdyOpenTypeName?: string
  lat?: number
  lng?: number
  mainPurpsCdNm?: string
  maintAmt?: number
  mtnFeeAmt?: number
  mtnFeeStatCd?: string
  nlaM2?: number
  nlaPy?: number
  otherUnitName?: string
  outId?: string
  paidParkBaseCd?: string
  paidParkCnt?: string
  pkltTypeCd?: string
  pkltTypeName?: string
  prdChkDy?: string
  prdId?: string
  prdTrStatCd?: string
  recommend_id?: boolean
  rentAmt?: number
  rmdlYear?: number
  splyTypeCd?: string
  splyTypeName?: string
  stdFlrGlaM2?: number
  stdFlrGlaPy?: number
  stdFlrNlaM2?: number
  stdFlrNlaPy?: number
  subAddr?: string
  substaNearBy?: string
  totalParkingCnt?: string
  unitCfCd?: string
  unitCfName?: string
  unitId?: string
  unitName?: string
  useAprDay?: string
  wcTypeName?: string

}
