
/**
*
* Generated by Rsquare Codegen (v3.0.1) (2022-07-22 14:26:31 184)
*
*/

export default interface WwwPostQusIn {

  bldId?: string
  email?: string
  mbrId?: string
  nonmemName?: string
  nonmemYn?: string
  qusCtn: string
  qusId?: string
  qusInflRoutCd: string
  qusTypeCd: string
  telNum?: string

}
